### ISSUE TITLE
PPA for Ubuntu Focal 20.04

### ISSUE THREAD

**Issue by AdamIsrael** [regolith-linux/regolith-desktop#203] opened 2020-01-31 18:04 UTC
Would it be feasible to add Focal to the releases supported by regolith, for those of us running/testing the upcoming release of Ubuntu?

Thanks!

**Comment by kgilmer** [comment] 2020-02-01 03:57
Hi @AdamIsrael , yeah that will have to happen sooner or later.  I'll update the ticket when I have something you can try out. :smile:

**Comment by kgilmer** [comment] 2020-02-17 16:31
Hi @AdamIsrael , I have staged `Focal` packages in `ppa:regolith-linux/unstable` for testing.  I've only looked at it for a few minutes, seems like there is a regression regarding desktop icons.  If you find other issues please add them here!

**Comment by sedrik** [comment] 2020-02-26 06:42
Hi just a quick note.

I found `https://launchpad.net/~kgilmer/+archive/ubuntu/regolith-unstable` when googling which doesn't work with focal. Maybe that one can be removed?

`ppa:regolith-linux/unstable` worked. Will report if I run into any issues.

**Comment by sedrik** [comment] 2020-03-11 07:35
I have gotten two issues pop up (sadly I can not say what triggered them).

In my statusbar I get a number of textual representation of glyphs instead of the actual glyphs. So I get `typeface_bar_glyph_help` instead of the actual symbol.

My Rofi is messed up and all I get is a black screen, I can still use it but don't see what I am typing or what the found values are.

I'm guessing I have a bad/stale config somewhere and some package is missing for the glyphs but I have not had time to investigate it further. If anyone has any pointers that would be great. I suspect that atleast the glyph error is because a missing dependency?

**Comment by kgilmer** [comment] 2020-03-12 02:29
Hi @sedrik :smile: .  Thanks for the detailed report.  I have not been keeping the Focal packages up to date along with Bionic and Eoan, simply for lack of time.  I'll update this ticket once I've done that, which should fix at least some of your problems.

**Comment by kgilmer** [comment] 2020-03-14 22:31
@sedrik , I've just synchronized fossa from eoan.  Can you update from unstable and try again?

**Comment by AdamIsrael** [comment] 2020-03-15 01:22
For me, the latest update fixes a ton of issues I was having, so thanks for that!

**Comment by sedrik** [comment] 2020-03-18 07:42
I did update but no change. I will look at wiping my configs too see if that solves it.

**Comment by kgilmer** [comment] 2020-04-07 15:41
Closing as now ppa:regolith-linux/unstable hosts focal packages.

**Closed by kgilmer** 2020-04-07 15:41 UTC
Labels: distro-support
