### ISSUE TITLE
i3 bar empty after reinstallation

### ISSUE THREAD

**Issue by KuroCat56** [regolith-linux/regolith-desktop#457] opened 2020-06-30 19:36 UTC
**Problem**: Status Indicators in i3 bar don't show up in 1.4.1 version
**Ubuntu version:** 18.04.4 LTS x86_64

I have been using Regolith in my laptop for a few weeks and today I updated to the new 1.4.1 version and the i3bar changed and didn't show any icons/status. I tried reinstalling Regolith following the steps in the documentation but it kept with the same problem.
A screenshot of the bar:

![image](https://user-images.githubusercontent.com/60792314/86167287-81fe1680-bad3-11ea-855e-d389082e29d3.png)

I tried installing some Status Indicators but nothing changed, except the _apt search i3xrocks-_ output:

```
apt search i3xrocks-
Sorting... Done
Full Text Search... Done
i3xrocks-battery/bionic,now 3.0.21-1 amd64 [installed]
  Indicator to show battery status.

i3xrocks-cpu-usage/bionic 3.0.21-1 amd64
  Indicator to show CPU load.

i3xrocks-focused-window-name/bionic 3.0.21-1 amd64
  Indicator to show focused window name.

i3xrocks-key-indicator/bionic 3.0.21-1 amd64
  Indicator for caps and num lock status.

i3xrocks-keyboard-layout/bionic 3.0.21-1 amd64
  Indicator to show keyboard layout.

i3xrocks-media-player/bionic 3.0.21-1 amd64
  Indicator to manage media playback.

i3xrocks-memory/bionic 3.0.21-1 amd64
  Indicator to show memory utilization.

i3xrocks-net-traffic/bionic 3.0.21-1 amd64
  Indicator to show network I/O status.

i3xrocks-nm-vpn/bionic 3.0.21-1 amd64
  Network manager VPN indicator.

i3xrocks-openvpn/bionic 3.0.21-1 amd64
  Indicator to show openvpn status.

i3xrocks-temp/bionic 3.0.21-1 amd64
  Indicator for system temperature.

i3xrocks-time/bionic,now 3.0.21-1 amd64 [installed]
  Indicator to show date and time.

i3xrocks-volume/bionic 3.0.21-1 amd64
  Indicator to show volume.

i3xrocks-weather/bionic 3.0.21-1 amd64
  Indicator to show local weather.

i3xrocks-wifi/bionic 3.0.21-1 amd64
  Indicator to display wifi router name.

regolith-i3xrocks-config/bionic,now 3.0.21-1 amd64 [installed,automatic]
  Regolith configuration for i3xrocks launcher

regolith-i3xrocks-focused-window-name/bionic 2.2.14-1ubuntu1~ppa1 amd64
  Blocklet to show focused window name.
```
Apparently the Status I installed are there but don't show up in the bar and I don't understand how to fix the problem nor how to configure efficiently the i3 bar

**Comment by kgilmer** [comment] 2020-07-02 04:51
Hi @KuroCat56 hmm, first I'd check to see if you have a custom i3 config file:

```bash
$ i3 --moreversion
```

If this returns something other than `/etc/regolith/i3/config` then you have a custom i3 config file.  If this is the case, you can either revert to the default by removing `~/.config/regolith/i3/config` (and log back in) or if you want to keep your custom i3 config file, you'll need to update the line in which i3xrocks is loaded.  [See here](https://github.com/regolith-linux/regolith-i3-gaps-config/blob/master/config#L515) for the correct invocation.  You may also want to use a diff tool to merge changes if you have a lot of customization or you are upgrading from an early version of Regolith.

If you do not have a custom i3 file then something else is going on.  Please let me know if this is the case.

**Comment by KuroCat56** [comment] 2020-07-02 15:45
This is what a got:
```
i3 --moreversion
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 4178)abort…)
Loaded i3 config: /etc/regolith/i3/config (Last modified: dom 03 may 2020 21:37:41 CST, 5140859 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

```
Unfortunately, I checked and I don't have any custom i3 file

**Comment by moritzheiber** [comment] 2020-07-07 08:05
Are there any error messages in the syslog or other places? Do you have any specific `Xresources` set as an override (e.g. in `~/.Xresources` or `~/.config/regolith/Xresources`)?

**Comment by kgilmer** [comment] 2020-07-09 22:09
In addition to @moritzheiber 's question, what do you get when running the following command from a terminal @KuroCat56 ?

```bash
i3xrocks -u ~/.config/regolith/i3xrocks/conf.d -d /etc/regolith/i3xrocks/conf.d
```

**Comment by walkabout21** [comment] 2020-07-14 00:22
I'm having the same issue running Ubuntu 19.10 with regolith desktop on Dell latitude 5490.  Removed local .config/regolith files but issue persists.

**Comment by kgilmer** [comment] 2020-07-19 15:36
What do you get when running the command in the comment above yours @walkabout21 ?

**Comment by walkabout21** [comment] 2020-07-19 18:56
@kgilmer I'm not sure what happened but I have run through this a few times, deleting any local config, including the auto created flags and restarting.  The i3xrocks command from the above comment would hang at the first "<span> </span> output line and the bar would only show the workspaces and the notifications bell.  I had copied the /etc/regolith to my .config folder to see if I could modify any of the config files or if the conf.d location was an issue.  So after I got your question I removed the .config regolith folder again, restarted and it is now fixed and working fine. In the interim I had removed a config file that was in the etc/regolith/i3xrocks folder and didn't appear in a fresh install I have on another machine, and also installed the i3 bar indicators separately, but after several restarts, that did not appear to have any affect. I'm scratching my head going through the syslogs to figure out what is different between today and yesterday.

**Comment by kgilmer** [comment] 2020-07-19 20:29
Hmm, ok well if it helps to debug in the future, running `i3xrocks -u ~/.config/regolith/i3xrocks/conf.d -d /etc/regolith/i3xrocks/conf.d` will let you test your changes without having to log back in.  

@KuroCat56 any update?

**Comment by KuroCat56** [comment] 2020-07-26 02:45
Yes, and my guess is Regolith last version doesn't go well with Ubuntu versions below 20. I have tried configuring the same things I did in Regolith with Ubuntu 20 and it goes pretty well, I don't have any visual bug with the bar.

**Comment by kgilmer** [comment] 2020-07-31 14:22
Hmm, not sure what could be @KuroCat56 without more information.  I use Regolith on Ubuntu 18.04 on a daily basis for work and do not have any issues with status indicators.  I'll close this for now but if you add debugging info, please re-open.

**Closed by kgilmer** 2020-07-31 14:22 UTC
Labels: configuration

**Comment by abisco5** [comment] 2020-10-18 11:48
Hey there,
Reopening cause I have a really similar issue and I'm not managing to fix it.
I've just upgraded to Ubuntu 20.04 after quite a while away from the distro and wanted to try again regolith (1.4). I'm thinking that the problem could be caused by my past configs of regolith/i3-GNOME that could have persisted and create some conflicts, but even after I try to remove them all and reinstall the package the problem persist.
On the i3bar I cannot see any icon/status, not even the time, only the workspace numbers (like op picture). Searched a bit for debugging and I tried solution here and on #323.
Debugging info:
```
➜  ~ apt search i3xrocks-
Sorting... Done
Full Text Search... Done
i3xrocks-battery/focal,now 3.0.21-1 amd64 [installed]
  Indicator to show battery status.

i3xrocks-cpu-usage/focal,now 3.0.21-1 amd64 [installed]
  Indicator to show CPU load.

i3xrocks-focused-window-name/focal 3.0.21-1 amd64
  Indicator to show focused window name.

i3xrocks-key-indicator/focal 3.0.21-1 amd64
  Indicator for caps and num lock status.

i3xrocks-keyboard-layout/focal,now 3.0.21-1 amd64 [installed]
  Indicator to show keyboard layout.

i3xrocks-media-player/focal 3.0.21-1 amd64
  Indicator to manage media playback.

i3xrocks-memory/focal,now 3.0.21-1 amd64 [installed]
  Indicator to show memory utilization.

i3xrocks-net-traffic/focal,now 3.0.21-1 amd64 [installed]
  Indicator to show network I/O status.

i3xrocks-nm-vpn/focal 3.0.21-1 amd64
  Network manager VPN indicator.

i3xrocks-openvpn/focal 3.0.21-1 amd64
  Indicator to show openvpn status.

i3xrocks-temp/focal 3.0.21-1 amd64
  Indicator for system temperature.

i3xrocks-time/focal,now 3.0.21-1 amd64 [installed]
  Indicator to show date and time.

i3xrocks-volume/focal,now 3.0.21-1 amd64 [installed]
  Indicator to show volume.

i3xrocks-weather/focal 3.0.21-1 amd64
  Indicator to show local weather.

i3xrocks-wifi/focal,now 3.0.21-1 amd64 [installed]
  Indicator to display wifi router name.

regolith-i3xrocks-config/focal,now 3.0.21-1 amd64 [installed,automatic]
  Regolith configuration for i3xrocks launcher
```
```
➜  ~ i3 --moreversion
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 3501)abort…)
Loaded i3 config: /home/bisco/.config/regolith/i3/config (Last modified: Sat 17 Oct 2020 02:46:24 CEST, 118696 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```
```i3xrocks -u ~/.config/regolith/i3xrocks/conf.d -d /etc/regolith/i3xrocks/conf.d``` seems to work, only on terminal I cannot see properly the icons for e.g. battery, etc, (probably font, icons pack issue), but I see the full output that should be there on the bar with every i3xrocks compontent installed.

From my understanding I have opened up ~/.config/regolith/i3/config and what seems unusual is that under i3xrocks config file ```set $i3xrocks_config /etc/regolith/i3xrocks/config``` (that should be the original line I had on a clean install, I've tried to change it quite a bit without managing to make it work) seems to be pointing to a file that is missing.
```
➜  ~ ls /etc/regolith/i3xrocks 
conf.d
```
Here I have only the conf.d dir, no config file even inside the dir.
Have you got any idea on how I could fix this? Thanks

**Comment by mikaben89** [comment] 2020-11-02 15:30
Hi @abisco5 did you get to fix your problem ? 
I followed instructions from same thread as you did and  the output of ` ~ apt search i3xrocks-` is similar to yours but for some reason, nothing's showing in the bar.

Thanks

**Comment by abisco5** [comment] 2020-11-02 21:46
Hey @mikaben89, I did not recieve updates here because it's a closed issue. Anyway tried on Slack and a suggestion has been helpful. Simply try to move/delete the Regolith folder under `~/.config`. Then logout and on subsequent login I had the bar working with default configs (based on the i3rocks packages I installed). You can then add your own config back bit by bit. Probably my problem was that the config file persisted from an older installation of Regolith. Hope it can help

**Comment by mikaben89** [comment] 2020-11-03 09:52
Hi @abisco5 , Thanks for the help, I appreciate it. Unfortunately your solution didn't work for me. The regolith dir under .config did regenerate itself but only contains a flag dir containing those files. 'first-time-setup-r1-4-1  show-shortcuts  term-profile  ui-fingerprint'. And what is also weird is that under /etc/regolith/i3xrocks/conf.d/ I do have those config files '30_net-traffic  40_cpu-usage  90_time'...

**Comment by kgilmer** [comment] 2020-11-03 16:00
@mikaben89 this command is just how i3 is configured to run i3xrocks (which runs the scripts and pipes it to the bar): `i3xrocks -u ~/.config/regolith/i3xrocks/conf.d -d /etc/regolith/i3xrocks/conf.d`.  It passes two directories, it looks for files in the first, and if it finds them it ignores the second directory.  If it does not find files in `~/.config/regolith/i3xrocks/conf.d` then it goes to the latter directory.  Running the script from the terminal should provide some clues, please paste the output you get into a new issue.
