### ISSUE TITLE
Laptop with external monitor for main output (lid closed), goes to sleep mode on log in

### ISSUE THREAD

**Issue by fostiropoulos** [regolith-linux/regolith-desktop#511] opened 2020-11-23 19:50 UTC
Describe the bug
I have an external monitor connected to a laptop (with the screen closed on the main laptop). Whenever I log in to regolith it goes to sleep mode. To clarify, when this happens I use an external monitor to log in and the lid remains closed.

To Reproduce
You will need a laptop and an external monitor. Power on laptop, connect external monitor, close laptop lid, log in on regolith and observe the laptop shutting down. 

Expected behavior
The laptop shouldn't power off after log in.

Screenshots
Not applicable 

Configuration file(s)
No customization

Installation Details

Regolith Install Type: [PPA]
Regolith Version: [1.5]
PPA url: [default: ppa:regolith-linux/release]
Host OS (for PPA): [Ubuntu 18.04]

**Comment by moritzheiber** [comment] 2020-11-24 08:26
Have you configured the laptop to stay awake in the event the lid is closed? There are several options you can set via `gsettings` here: https://askubuntu.com/questions/1059705/keep-a-laptop-running-with-closed-lid#1059712

**Comment by fostiropoulos** [comment] 2020-11-24 15:31
@moritzheiber correct. It works fine if I open the lid, log in and then close the lid. But I can't log in with the lid closed.

**Comment by kgilmer** [comment] 2020-11-25 03:54
To confirm, @fostiropoulos did you try any of the gsettings commands listed on the page @moritzheiber provided?  This may be the one you need:
```
gsettings set org.gnome.settings-daemon.plugins.power lid-close-suspend-with-external-monitor 'nothing'
```

**Comment by kgilmer** [comment] 2020-11-25 03:56
Reading you're issue more closely, this issue may have something that will address your problem if you're using lightdm: https://askubuntu.com/a/739425/834410

Did you install Regolith via ISO or PPA @fostiropoulos ?

**Comment by fostiropoulos** [comment] 2020-11-26 17:52
@kgilmer I already had the settings suggested by the article. I installed via PPA. The problem is if I go to lock screen (ie `host_key + escape`) I can log back in normally. However if I log out ie `host_key + shift + e` I go back to the ubuntu log in screen. If I log in to an account with regolith the computer will go to sleep. If I log in to regular ubuntu without regolith the computer will log in normally.

Now when the laptop does go to sleep and I log in without reboot, regolith is broken completely ie I get error code 103 on the bottom right corner. It is a weird bug I must admit. Let me know if I can provide any logs or anything else more helpful.

**Comment by kgilmer** [comment] 2021-03-10 04:49
@twvd you could verify this behavior by seeing if it can be reproduced in the gnome-flashback desktop session.  To do that:

sudo apt install gnome-session-flashback
After installation, reboot. In the login prompt, choose GNOME Flashback (Metacity).

If it turns out to be an issue w/ gnome-flashback we can file an issue upstream and see if there are any workarounds.

**Comment by twvd** [comment] 2021-03-12 12:12
Interestingly enough I can't seem to reproduce the issue at all now, even on the Regolith session. Ohwell, I'll do some more tests if it pops up again.

**Comment by kgilmer** [comment] 2021-03-23 03:48
works for me. I'll close it but feel free to re-open when/if it comes back.

**Closed by kgilmer** 2021-03-23 03:48 UTC
Labels: configuration, question
