### ISSUE TITLE
Settings dialog freezes and change not implemented when selecting a different mouse cursor size

### ISSUE THREAD

**Issue by savaged** [regolith-linux/regolith-desktop#415] opened 2020-05-22 11:36 UTC
**Describe the bug**
Settings dialog freezes and change not implemented when selecting a different mouse cursor size.

**To Reproduce**
Open Settings. Select Universal Access. Select Cursor Size and pick a different size. Try to leave that pop-up. The Settings application is frozen and no change is made.

**Expected behavior**
The mouse cursor size changes and the Settings application is available.

**Installation Details**
 OS: Ubuntu 20.04 focal
Kernel: x86_64 Linux 5.4.0-31-generic
Shell: bash 5.0.16
Resolution: 3286x1080
DE: GNOME 3.36.2
WM: i3
GTK Theme: Ayu-Mirage-Dark [GTK2/3]
Icon Theme: Moka
Font: Cantarell 11
Disk: 48G / 114G (45%)
CPU: Intel Core i3-2350M @ 4x 2.3GHz [52.0°C]
GPU: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)
RAM: 1229MiB / 7844MiB

**Additional context**
Fresh full install of Regolith OS

**Comment by moritzheiber** [comment] 2020-05-22 11:42
Could you please try out to install an updated `gnome-flashback` from `focal-proposed`? https://github.com/regolith-linux/regolith-desktop/issues/406#issuecomment-629674629

Adding the `focal-proposed` repository can easily be achieved by running "Software & Updates", switching to the "Developer Options" tab, ticking the box next to "Pre-released updates", clicking on "Close" and then letting the system reload the package definitions.

Then follow the instructions in the comment I posted.

Thanks!

**Comment by savaged** [comment] 2020-05-23 07:26
Followed the steps. No change.

**Comment by moritzheiber** [comment] 2020-05-23 08:30
@muktupavels Could this be an issue with `gnome-flashback`?

**Comment by moritzheiber** [comment] 2020-05-23 08:32
@savaged Could you try moving the GNOME settings window and see whether the cursor size selection window is "behind" it? I think we're dealing with a focus change that "hides" the cursor selector behind the settings window (and since it's a "child" of the settings window it'll capture all input, without being visible)

**Comment by muktupavels** [comment] 2020-05-23 09:22
Most likely, no. Mentioned thing changes `org.gnome.desktop.interface cursor-size` setting. It is handled by `metacity` not `gnome-flashback`.

https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/master/panels/universal-access/cc-ua-panel.c#L339
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/blob/master/plugins/xsettings/gsd-xsettings-manager.c#L766
https://gitlab.gnome.org/GNOME/metacity/-/blob/master/src/core/prefs.c#L754
https://gitlab.gnome.org/GNOME/metacity/-/blob/master/src/core/display.c#L5139

Cursor size is also set as XResource - Xcursor.size:   
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/blob/master/plugins/xsettings/gsd-xsettings-manager.c#L829

It is used by compiz:
https://git.launchpad.net/compiz/tree/src/screen.cpp#n1428

Quickly testing seems to work in both GNOME Flashback sessions.

Also does it really freeze? It is modal dialog - main window is not usable while cursor dialog is open. 

For some reason in first test I had no decorations for cursor dialog, so I was not able to close it, but otherwise everything worked. Can not reproduce missing decorations again...

Cursor size not changing will be i3 bug/problem.

**Comment by moritzheiber** [comment] 2020-05-23 09:51
@muktupavels Here's a short video of what's happening, just for illustration purposes:
![Peek 2020-05-23 11-43](https://user-images.githubusercontent.com/616813/82727514-3d6ca780-9ceb-11ea-9e70-74db5e4dff0a.gif)

Here are the steps I took:
1. Open the settings dialog for Universal Access
2. Click on "Cursor Size" > Modal for selecting the size pops up
3. Select any cursor size > Modal stays open
4. Click back on the settings dialog > Modal for cursor size selection "disappears"
5. I cannot interact with the settings dialog at all, except for moving its window
6. I move the window away from its position to reveal the "hidden" child modal for the cursor size selection "underneath" it
7. I close the cursor size selection (using Mod+Shift+Q)
8. I can interact with/close the settings dialog now

So my question is: Is this gnome-flashback/gnome-settings related, because it "removes" an attribute from the cursor size selector? Or is it a "bug" in i3, which lets the window "disappear" behind the settings dialog?

**Comment by savaged** [comment] 2020-05-23 10:12
I have followed the steps @muktupavels shared. The dialogue issue is one thing but the setting still doesn't update the cursor size. Seems like two issues, so perhaps this should be split?

**Comment by moritzheiber** [comment] 2020-05-23 10:20
@savaged No, the changing of the cursor size is "invalid" since the GNOME settings dialog cannot be used with i3/without metacity directly, unless you're interpreting the `Xcursor.size` `Xresources` variable, as Alberts mentioned .. one could file an enhancement issue for respecting the `Xcursor.size` variable though (unless there isn't an existing variable already one could use instead)

**Comment by moritzheiber** [comment] 2020-05-23 10:44
@savaged On second though, even if I set `Xcursor.size` manually in `Xresources` it's not being respected, so I think you're right, this is a second bug. Would you mind filing it? As an added benefit, the settings dialog for cursor size should be working once the `Xcursor.size` bug is fixed ..

**Comment by savaged** [comment] 2020-05-23 11:10
will do

**Comment by muktupavels** [comment] 2020-05-23 19:57
Cursor dialog "disappearing" under main window is WM bug:
- https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/master/panels/universal-access/cc-ua-panel.ui#L1070   
- https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-modal

Cursor dialog is modal and transient parent is also set. Works as expected, no? You can not interact with main window while cursor dialog is open... It does not freeze. :)

Cursor not changing size is other bug. Your WM needs to do same thing what metacity or compiz does.

**Comment by savaged** [comment] 2020-05-24 08:03
At first the pop up is visible but after a selection is made it drops behind the main dialog and thus gives the impression the main Settings dialog is frozen. One has to move the main dialog to see the popup is still there and has focus. Just a usability issue, but I thought Regolith was aiming at being a user friendly distro.

**Comment by moritzheiber** [comment] 2020-05-24 08:35
@savaged Please stop insinuating we aren't making an effort to resolve this (as you also did with the other bug). As @muktupavels mentioned, this appears to be a bug in the window manager, which Regolith has no control over. We'll have to mention this upstream, but it'll take a little longer than as if we were solving a bug we ourselves introduced/caused

**Comment by savaged** [comment] 2020-05-24 08:42
@moritzheiber Apologies; I misunderstood. Good to know there's a positive approach here.

**Comment by moritzheiber** [comment] 2020-05-24 08:42
@kgilmer I think we need to rollout the latest i3-gaps release (4.18.1) in order to make sure aren't hitting a bug that's already resolved in i3

**Comment by kgilmer** [comment] 2020-09-05 20:18
@moritzheiber @savaged i3-gaps 4.18.2 is now available in `unstable` and `speed-ricer` PPAs.  I have verified that the modal cursor selection dialog does not fall behind the control panel as illustrated in the video.  However the cursor size remains unchanged.

**Comment by moritzheiber** [comment] 2021-01-02 14:25
@kgilmer Interestingly enough, I cannot confirm that this is indeed fixed already .. maybe we need to re-verify?

**Comment by kgilmer** [comment] 2021-01-02 16:54
I was able to change cursor size in focal by selecting the cursor from settings and then reloading i3:

![image](https://user-images.githubusercontent.com/49683/103462128-09715000-4cd8-11eb-8a6f-5383d3f4cc47.png)


Is there something I'm missing?

**Comment by moritzheiber** [comment] 2021-01-02 17:14
@kgilmer Interesting. The cursor size does not change for me, and if I click inside the settings window while the cursor modal is still visible it still "vanishes" behind the settings window (like it's shown in the video). I wonder what the differences are? :thinking:

**Comment by savaged** [comment] 2021-01-02 18:16
I can confirm that this now works correctly.

**Comment by justinmoon** [comment] 2021-01-08 22:22
The first time I tried this cursor size selection in settings it didn't work.

But I went to the Tweaks app and noticed that "cursor" here wasn't set to anything. I clicked it and selected the only option -- "Pop". Reloaded i3 and now it works.

**Comment by kgilmer** [comment] 2021-02-16 05:16
Closing as resolved

**Closed by kgilmer** 2021-02-16 05:16 UTC
Labels: bug, i3-bug, verified
