### ISSUE TITLE
Scaling switching bug

### ISSUE THREAD

**Issue by hypergig** [regolith-linux/regolith-desktop#289] opened 2020-03-24 17:32 UTC
![IMG_20200323_082235](https://user-images.githubusercontent.com/8643560/77457627-53391b80-6dd3-11ea-82db-6f2a8180589b.jpg)

When I switch between laptop screen (scale 2) and desktop screen (scale 1), this happens to me. @kgilmer mentions it's a known flashback bug, just wondering if anyone has figured out a workaround for it. Maybe a script or command, something I can add to my i3 config with exec always to fix it when I restart i3, something I always have to do anyway when switching between displays.

**Comment by kgilmer** [comment] 2020-03-24 19:41
To clarify, the issue is that you are seeing your wallpaper image tiled instead of zoomed?  On both displays?

**Comment by hypergig** [comment] 2020-03-24 20:25
I think it's deeper than that. Yes the wallpaper is tiled.. but screenshots _only_ work in the top left quadrant. It's like the other 75% of the screen goes somewhere else and I can't capture them.

Screen-share apps (like zoom) still work as expected.

**Comment by moritzheiber** [comment] 2020-05-22 18:15
@hypergig Could you give the `gnome-flashback` update from `focal-proposed` a try? https://github.com/regolith-linux/regolith-desktop/issues/406#issuecomment-629674629
Let us know how it goes.

**Comment by hypergig** [comment] 2020-05-26 13:55
@moritzheiber sure thing! I will let you know how it goes

**Comment by hypergig** [comment] 2020-06-22 16:25
@moritzheiber I am installing focal today, will this get me the update automatically or do I need to do some fancy apt getting of things?

**Comment by moritzheiber** [comment] 2020-06-22 16:31
@hypergig I’m not entirely sure whether the proposed update has made its way into the regular repositories yet. If in doubt, follow the instructions from above.

**Comment by moritzheiber** [comment] 2020-06-23 15:01
@hypergig I just confirmed that the version I'm seeing in `focal-updates` is the one that was submitted to `focal-proposed`, so you should be able to just install `3.36.3-0ubuntu1` from the regular channels and try out whether it fixes the issue for you.

**Comment by hypergig** [comment] 2020-06-24 21:21
thank you @moritzheiber I will let you know how it goes when I get around to it

**Comment by muktupavels** [comment] 2020-06-27 21:35
This should be fixed in focal.

Screenshot bug probably is/was fixed with https://gitlab.gnome.org/GNOME/gtk/-/commit/489fb1783b8e3544db36eeb8d14e31ac1afaa0f1.

Background bug related commits:
https://gitlab.gnome.org/GNOME/gnome-desktop/-/commit/666ddf4d78560711f1f56c3deee195bc708b5400
https://gitlab.gnome.org/GNOME/gnome-flashback/-/commit/72d83ec5f3ca6d4d2701cd5eea430ae9c22c92b1

**Comment by moritzheiber** [comment] 2020-06-28 09:37
@hypergig Did you have a chance to try out the update `gnome-flashback` package?

**Comment by muktupavels** [comment] 2020-06-28 09:41
If he was already using 3.36.0 and had problem then 3.36.3 will have same problem...

**Comment by moritzheiber** [comment] 2020-06-28 09:45
@muktupavels Understood, it just sounded like as if you considered it fixed in `focal` as per you earlier comment.

**Comment by muktupavels** [comment] 2020-06-28 09:53
Yes, it should be fixed in `focal`. But it does not matter if it is 3.36.0 or 3.36.3 from `focal-updates` in this case.

**Comment by hypergig** [comment] 2020-06-29 18:01
So, the wall paper bug looks fixed however, the screenshot bug is not and there is a new bug:

If you try to take a selection screenshot (shift-print screen), it will fail everywhere _except_ the top left quadrant and indeed if you take a full screen screen shot you only get that corner:

![Screenshot from 2020-06-29 13-56-23](https://user-images.githubusercontent.com/8643560/86039374-57975500-ba10-11ea-99f9-948765fac9ba.png)

It's almost like the screen shot utility doesn't understand the size of the screen anymore.

The new bug seems to happen the first time you connect your laptop to your external display. The full lock screen only takes up the top left quadrant, exposing the rest of your desktop (the other 75% of it). This only happens the first time, the next time you lock your computer the whole screen is covered. I will try to get a photo of it too.

**Comment by hypergig** [comment] 2020-06-29 18:03
So, the wall paper bug looks fixed however, the screenshot bug is not and there is a new bug:

If you try to take a selection screenshot (shift-print screen), it will fail everywhere _except_ the top left quadrant and indeed if you take a full screen screen shot you only get that corner:

![Screenshot from 2020-06-29 14-02-32](https://user-images.githubusercontent.com/8643560/86039958-3aaf5180-ba11-11ea-9370-800c7f1485c4.png)

It's almost like the screen shot utility doesn't understand the size of the screen anymore.

The new bug seems to happen the first time you connect your laptop to your external display. The full lock screen only takes up the top left quadrant, exposing the rest of your desktop (the other 75% of it). This only happens the first time, the next time you lock your computer the whole screen is covered. I will try to get a photo of it too.

**Comment by muktupavels** [comment] 2020-06-29 18:08
@hypergig Is that with Ubuntu 20.04 / focal?

Lock screen problem might be fixed with this - https://gitlab.gnome.org/GNOME/gnome-flashback/-/commit/cdc534a3b0f4abe4e02a5397466ae094ee3d7fdc. This fix is NOT in focal!

**Comment by hypergig** [comment] 2020-06-30 13:11
Very strange but after a few dockings and undockings from my external monitor, the screenshot issues eventually stopped happening. This is without a reboot, which is usually the fix.

**Comment by hypergig** [comment] 2020-07-01 11:45
Ok, so I narrowed down the screenshoot bug. It _only_ happens when my computer is suspended while _not_ plugged into my external monitor, and is later resumed while plugged in. If I first resume my computer before plugging it in, everything seems fine.

So the bug is around with how flashback deals with changes to scale and state while suspended. Which is honestly, is pretty understandable. I don't think anything handles that sort of transition very well.

**Comment by hypergig** [comment] 2020-07-01 11:52
> @hypergig Is that with Ubuntu 20.04 / focal?

yep
```
            .-/+oossssoo+/-.               jordan@jordan-ThinkPad-T480
        `:+ssssssssssssssssss+:`           ---------------------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: 20L5CTO1WW ThinkPad T480
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-39-generic
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 21 hours, 58 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1966 (dpkg), 20 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.16
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 5120x1440
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Regolith
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: i3
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Solarized-Dark-Orange [GTK3]
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: DMZ-Black [GTK3]
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: x-terminal-emul
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel i7-8650U (8) @ 4.200GHz
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: Intel UHD Graphics 620
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce MX150
      -+sssssssssssssssssyyyssss+-         Memory: 7370MiB / 31863MiB
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.

```

**Comment by hypergig** [comment] 2020-07-06 15:21
Got a picture of the lock screen bug:
![s](https://user-images.githubusercontent.com/8643560/86610018-be6dbe80-bf7a-11ea-8992-1f5945ddc9a5.jpg)

**Comment by muktupavels** [comment] 2020-07-07 10:59
Do you know how to rebuild debian package? Lock screen problem should be fixed by mentioned commit in previous comment.

For screenshot bug, please open upstream issue. When I will have time I will try to reproduce problem.

**Comment by hypergig** [comment] 2020-07-13 14:03
`exec_always --no-startup-id xrandr -s 1 && xrandr -s 0` fixes the screenshot bug

**Comment by hypergig** [comment] 2020-07-23 13:38
FWIIW, I took to writing a script that gets used with an `exec_always` that will fix my session when I refresh i3

https://github.com/hypergig/workstation/blob/master/bin/i3-refresh

A few things go haywire when the scale changes on my computer, ie I move to and from clamshell mode, including my bar so this became necessary for other reasons.

**Comment by kgilmer** [comment] 2021-02-16 05:04
Closing this as not clear if anything actionable.  Please reopen if needed.

**Closed by kgilmer** 2021-02-16 05:04 UTC
Labels: bug, feedback wanted, gnome
