### ISSUE TITLE
Where is the suckless terminal installed by default??

### ISSUE THREAD

**Issue by inigoval** [regolith-linux/regolith-desktop#80] opened 2019-08-02 10:46 UTC
This is driving me nuts - nowhere is it documented in the regolith wehre they've installed the default terminal (st) which means i cant change the damn config.h file!!

please tell me where the st directory is, i've checked most common paths like /usr/share

**Comment by kgilmer** [comment] 2019-08-02 14:49
Hi @inigoval :smile: 

The binary for st is stored in `/usr/bin/st`.  Here are a couple of ways that might help you in the future.  st is launched by i3wm when you hit <super>-<enter> so it needs to be somehow referenced in the i3 config file.  To find the current i3 config file:
```
$ ps aux | grep i3  # search processes that contain i3
...
kgilmer  16831  0.0  0.0  51320 19072 tty2     S+   Aug01   0:06 i3 -c /home/kgilmer/.config/i3-regolith/config-4.16-1ubuntu18ppa11
```

So if we search the i3 config file for st we find:
```
$ cat /home/kgilmer/.config/i3-regolith/config-4.16-1ubuntu18ppa11 | grep exec | grep st
bindsym $mod+Return exec /usr/bin/st
...
```

So, that's where i3 lauches st from.  If you make your own version of st, you'll need to replace `/usr/bin/st` or, more conventionally, after building from source it would go into `/usr/local/bin` in which case you can simply update the path in the i3 config file.

A simpler way of finding any program on your path is:
```
$ which st
/usr/bin/st
```

And another super useful command that tells you which Debian packages provide a given file, try:
```
$ dpkg -S /usr/bin/st
regolith-st: /usr/bin/st
```

**Comment by inigoval** [comment] 2019-08-05 21:54
Thanks for your answer kgilmer!

**Comment by kgilmer** [comment] 2019-08-06 15:09
Closing, as seems like the issue is resolved but feel free to reopen if not.

**Closed by kgilmer** 2019-08-06 15:09 UTC
