### ISSUE TITLE
Debian Testing / Sid (bookworm) Support

### ISSUE THREAD

**Issue by jckso** [regolith-linux/regolith-desktop#635] opened 2022-05-02 00:37 UTC
- [x] I've [run a search on the existing enhancements](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [X] I've read [the Regolith documentation](https://regolith-linux.org/docs/https://regolith-linux.org/docs/) and didn't find any relevant topic
- [X] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Is your feature request related to a problem? Please describe.**
Although Debian Stable is great for certain use cases, many need to use Testing / Sid due to hardware incompatibilities, or many just want newer packages that aren't available in backports.

**Describe the solution you'd like**
Regolith's builds should target Debian bookworm. A separate repo specifically for bookworm is probably needed. When installing the release for bullseye onto bookworm, certain things do not work, such as terminal themes and hotkeys for apps. I believe this is due to the bullseye packages being installed onto bookworm, but more testing is probably needed.

**Additional context**
[Debian Testing ISO](https://cdimage.debian.org/cdimage/weekly-builds/amd64/iso-cd/debian-testing-amd64-netinst.iso)
There are no unstable images for Sid, but you can follow the instructions [here](https://wiki.debian.org/DebianUnstable)

**Comment by kgilmer** [comment] 2022-05-22 02:35
The builder is failing in an odd way (it builds the first package in the manifest and then silently exits from building remaining packages).  It's not clear to me why this is happening, but my guess is that an error within the build for a package is causing the loop to exit prematurely.  I see errors from `dch` saying that it does not recognize `bookworm` as a distribution.  It seems to be wanting a user confirmation from the console.  This seems like it might be impacting the loop but unsure.

Need to know how debian expects "testing" packages to be represented in a repo.  Did some googling but as usual there are so many false positives I quickly gave up looking for an answer.  If anyone can unlock the mystery of `dch` + debian testing I can continue this work.

**Comment by jckso** [comment] 2022-07-05 03:44
This could be a dumb question, but what debchange version are you using? Here's the [sourcecode](https://github.com/Debian/devscripts/blob/a743e0eafc5e47def3adc91d9f45f41267de41b0/scripts/debchange.pl) for debchange. It seems that bookworm is added.

**Comment by jckso** [comment] 2022-07-05 04:04
I think I might have found the answer to your first problem. In the [sourcecode](https://github.com/Debian/devscripts/blob/a743e0eafc5e47def3adc91d9f45f41267de41b0/scripts/debchange.pl) for debchange, it checks the distro name given
`if (defined $opt_D) {
    if ($vendor eq 'Debian') {
        unless ($opt_D
            =~ /^(experimental|unstable|sid|UNRELEASED|((old){0,2}stable|testing|wheezy|jessie|stretch|buster|bullseye)(-proposed-updates|-security)?|proposed-updates)$/
        ) {
            my $deb_info = get_debian_distro_info();
            my ($oldstable_backports, $stable_backports) = ("", "");
            if ($deb_info == 0) {
                warn`

Try running dch with `testing` as the distribution instead of `bookworm`

**Comment by gazsp** [comment] 2022-07-12 19:54
Is there any update on this? I'm on bookworm and installing the bullseye package doesn't fully work (as described in the parent comment).

**Comment by kgilmer** [comment] 2022-07-26 00:14
I'm looking for testers.  To test from testing/bookworm, follow the installation directions on regolith-desktop.com, but use this URL for apt: 

```
https://regolith-desktop.org/unstable-debian-testing-amd64
```

![Screenshot from 2022-07-25 17-13-41](https://user-images.githubusercontent.com/49683/180895791-74161235-6091-4053-a1b3-eab68f9cf12c.png)

**Comment by jckso** [comment] 2022-07-27 03:30
Just installed in a VM. Everything seems to be working great! I think settings not respecting theme is already a bug in other distros too. Will install on main computer later! 
<img width="1440" alt="Screen Shot 2022-07-26 at 11 29 09 PM" src="https://user-images.githubusercontent.com/64824845/181154558-aa9159b3-07e9-4a4d-aa7f-86877befd706.png">

**Comment by jckso** [comment] 2022-07-27 03:34
> To test from testing/bookworm, follow the installation directions on regolith-desktop.com, but use this URL for apt:

Also change `bullseye` to `testing`
`echo deb "[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] \
https://regolith-desktop.org/unstable-debian-testing-amd64 testing main" | \
sudo tee /etc/apt/sources.list.d/regolith.list`

**Comment by kgilmer** [comment] 2022-07-28 05:28
There is an issue with regolith-control-center:

```
$ sudo apt install i3xrocks-time 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 regolith-control-center : Depends: language-selector-gnome (>= 0.179~) but it is not installable
                           Depends: whoopsie-preferences but it is not installable
                           Recommends: libcanberra-pulse but it is not going to be installed
                           Recommends: power-profiles-daemon but it is not installable
                           Recommends: gnome-control-center-faces but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by kgilmer** [comment] 2022-07-30 22:29
An update has been pushed for `regolith-control-center`.  @jckso are you able to test that it works for you?

**Comment by jckso** [comment] 2022-08-03 04:32
@kgilmer Works for me! 
<img width="1271" alt="Screen Shot 2022-08-03 at 12 31 35 AM" src="https://user-images.githubusercontent.com/64824845/182524642-f95ace8f-b7f3-4bd7-91a8-a6bcf394087a.png">

**Comment by Giom-fm** [comment] 2022-08-14 15:58
So I installed it on now on barematel (Debian sid) and so far everything works. I'll test it for a few days and report back. Thanks for the feature!

**Comment by MHellmund** [comment] 2022-08-18 15:56
Many thanks for providing Regoltih2 packages for Debian sid! 

I didn't see the rofication notification counter in the i3xrocks bar. 
Reason: wrong netcat. 
I had to install netcat-openbsd (and not netcat-traditional) since only this version supports the 'nc -U' option used in  /usr/share/i3xrocks/scripts/rofication.

**Comment by kgilmer** [comment] 2022-08-20 17:26
Thanks for the reminder (I had this issue to but forgot to apply the fix to the package)

**Comment by kgilmer** [comment] 2022-08-20 17:43
I have been running bookworm for at least 3 weeks now without any problems.  Will promote the build target to `stable`.

**Comment by jckso** [comment] 2022-08-20 18:58
Is there anything different to do to support Sid, or is that included in testing? I know that some people have said Sid is already working.

**Comment by Giom-fm** [comment] 2022-09-01 10:17
I now have the first problems on sid. After an update the packets i3xrocks-updates i3xrocks-time disappeared. I must admit I was not fully present in the update process and blindly accepted everything...

When I try to install the packages the following error message appears.

3xrocks-time:
`The following packages have unmet dependencies:
 libgnome-desktop-3-19 : Depends: gnome-desktop3-data (< 43~) but 43~alpha-3 is to be installed`

and for i3xrocks-updates:
`The following packages have unmet dependencies:
 i3xrocks-updates : Depends: update-notifier-common but it is not installable`

Additionally, I noticed that the regolith-settings are no longer installed. However, I don't know the name of the package or can't find it to install it.

**Comment by Giom-fm** [comment] 2022-09-05 19:52
All right thanks for your efforts @kgilmer 

About the testing/unstable. I am unsure which distribution version of Debian the regolith test target is now tracking.
Is this just a target to test the development of regolith or should the target run "stable" on debian sid.

**Comment by kgilmer** [comment] 2022-09-05 21:53
I just read https://wiki.debian.org/DebianUnstable and from that believe that we'll only have time (at most) to support `testing`.  As I understand it Debian Sid represents `unstable` and given the expected amount of volatility there would not want to spend time dealing w/ triaging upstream issues.  So, the existing setup in Regolith I believe will carry forward: support both `bullseye` and `testing`, but the later will never make it to a Regolith `release` stage due to obvious reasons.

**Comment by kgilmer** [comment] 2022-09-06 05:03
I cannot get unmodified gnome-control-center to build in bookworm at this time due to outdated dependencies.  Will look back in a week or so to see if everything has stabilized enough to build from source.  I may also look into making `regolith-control-center` a soft dependency.

**Comment by Giom-fm** [comment] 2022-09-06 17:02
> I just read https://wiki.debian.org/DebianUnstable and from that believe that we'll only have time (at most) to support `testing`. As I understand it Debian Sid represents `unstable` and given the expected amount of volatility there would not want to spend time dealing w/ triaging upstream issues. So, the existing setup in Regolith I believe will carry forward: support both `bullseye` and `testing`, but the later will never make it to a Regolith `release` stage due to obvious reasons.

Yes, I can understand that. Fortunately, testing and sid are closely related, so hopefully there will be few complications.

> I cannot get unmodified gnome-control-center to build in bookworm at this time due to outdated dependencies. Will look back in a week or so to see if everything has stabilized enough to build from source. I may also look into making `regolith-control-center` a soft dependency.

Ok thanks!

**Comment by Giom-fm** [comment] 2022-09-22 16:18
I think you could give it a try. They have updated every gnome stuff to gnome 43.

**Comment by kgilmer** [comment] 2022-10-09 17:22
Progress: 

![image](https://user-images.githubusercontent.com/49683/194770641-3c6cf52a-1dba-459b-90db-593f39e94b76.png)

**Comment by Giom-fm** [comment] 2022-10-09 20:42
Great!
I just updated it and it fixed my mentioned issues.

**Comment by cosgroveb** [comment] 2022-11-17 02:49
Still looking for testers? Your bookworm apt repo URLs appear to 403.

**Comment by mpareja** [comment] 2022-11-17 03:59
@cosgroveb It just worked for me with the caveat that I installed Debian with Gnome Flashback installed - unsure if that matters. I used the following on this newly minted Debian machine:

```
$ cat /etc/apt/sources.list.d/regolith.list
deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.org/unstable-debian-testing-amd64 testing main
```

**Comment by mpareja** [comment] 2022-11-17 04:00
- [ ] unable to install regolith-look-solarized-dark

```
$ sudo apt install regolith-look-solarized-dark
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 solarc-theme : Depends: gnome-themes-standard but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by kgilmer** [comment] 2022-11-17 15:27
Hmm, this is working for me @mpareja .  Perhaps I have more apt repos?

```
~$ apt-cache policy | grep http | awk '{print $2" "$3}' | sort -u
http://deb.debian.org/debian testing/contrib
http://deb.debian.org/debian testing/main
http://deb.debian.org/debian testing/non-free
http://packages.microsoft.com/repos/code stable/main
https://packagecloud.io/slacktechnologies/slack/debian jessie/main
https://packages.microsoft.com/repos/vscode stable/main
https://regolith-desktop.org/testing-debian-testing-amd64 testing/main
https://repo.steampowered.com/steam stable/steam
o=https://regolith-desktop.org/testing-debian-testing-amd64,n=testing,l=https://regolith-desktop.org/testing-debian-testing-amd64,c=main,b=amd64 
~$ apt list | grep gnome-themes-standard

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gnome-themes-standard/now 3.28-1 all [installed,local]
```

@cosgroveb :
> Still looking for testers? Your bookworm apt repo URLs appear to 403.

Yeah that apt repos have no html content, but the `unstable` stage does have support for `debian testing`.  I'm running it at home as my primary dev environment FWIW.

**Comment by kgilmer** [comment] 2022-11-21 03:30
Hi @mpareja , somehow I have that package on `bookworm`.  It's in these, if you care to install that look: https://packages.debian.org/search?keywords=gnome-themes-standard

**Comment by BillyMorgan** [comment] 2022-11-22 20:59
Hey guys, I did a dumb thing yesterday and installed on top of Ubuntu 22.10 (Kinetic) before realising I was having the same issue mentioned above and then realising that 22.10 isn't officially supported. I only noticed something wasn't right because my clock wasn't showing in the bar. Then I saw this:

```
$ sudo apt install i3xrocks-time
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 regolith-control-center : Depends: libgnome-desktop-3-19 (>= 3.33.4) but it is not installable
                           Recommends: pulseaudio-module-bluetooth but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Is there anything I can do / help test? I really don't wanna have to re-install.. WAY too lazy :)

**Comment by BillyMorgan** [comment] 2022-12-07 10:25
I reinstalled :/ Sorry, not much help... it did fix it though!

**Comment by matthiasjg** [comment] 2023-01-24 17:37
I would like to help w/ testing on `arm64` (I just updated my ThinkPad X13s to `unstable`).

But in order to do so, the `testing-debian-testing-arm64` repository needs to setup and populated, of course.
Would this be possible? 

(I'm posting here, not on `regolith-linux/voulage` b/c of context).

**Comment by kgilmer** [comment] 2023-01-25 15:20
Hi @matthiasjg , yes I'll look into enabling this stage for your testing.  The first step is setting up a build host w/ the base OS to build packages.  Something like [this](https://github.com/regolith-linux/voulage/blob/main/.github/workflows/build-deb-v4.yml#L69-L73) but for `arm64`.

**Comment by sascha-wi** [comment] 2023-01-30 09:25
Hey I used a basic debian install and changed repositories to testing. After that I used the instructions on the regolith webpage to install its repository and packages. When logging into the Regolith session its not really useable, there is no application launcher and I can also not start the help page. There is a message on the bottom bar indicating something is not working either. I am able to open terminals though.

Now that I saw this issue, I changed the repository as mentioned by @kgilmer and did update & upgrade. Still the issues persist. Any help? Do I need to remove the packages beforehand?

**Comment by dinotheextinct** [comment] 2023-02-10 15:45
Two weeks without a response? Do I need to ping someone?

**Comment by kgilmer** [comment] 2023-02-10 16:47
There has been some unrelated build issues due to incoming Wayland work
that have prevented me from getting to this.  Will respond when I have
actionable steps.

**Comment by adamroyjones** [comment] 2023-06-10 18:10
I've been using Regolith with Bookworm on three different machines for the past few months. All's been well (aside from a quickly fixed issue with ~/.config/regolith2 becoming ~/.config/regolith3)—thank you for all of your hard work around this.

As Bookworm has now stabilised and released, is there an intention to formalise a release?

**Comment by kgilmer** [comment] 2023-06-11 16:32
> As Bookworm has now stabilised and released, is there an intention to formalise a release?

Yes, I've just [added](https://github.com/regolith-linux/voulage/commit/24c412c9cf411c04112b1e1bae673d9de67092fd) it as it's own target distinct from `testing` to the build system, so for 3.0 it will be supported :+1:

**Comment by Giom-fm** [comment] 2023-08-23 12:34
Today I was not able to update my machine:

Fehl:34 https://regolith-desktop.org/unstable-debian-testing-amd64 testing Release 404  Not Found [IP: 104.238.213.207 443]

Have i missed something. Still running debian unstable.

**Comment by kgilmer** [comment] 2023-08-23 14:38
You haven't missed anything.  Here is what happened:  Some recent upstream changes in Debian's wayland libraries have caused a build regression.  Then, the repository key expired.  I rebuilt all the packages to sign them with a new key but the `unstable` stage for Debian Testing has been disabled due to the wayland issue.  Debian Testing packages will return to the repo once the build regressions are resolved, however it's unlikely this will get any attention until after the 3.0 release is out the door.  (Debian Testing, by it's nature, is never part of a release)

**Comment by Giom-fm** [comment] 2023-08-31 07:16
Ok I have to wait then.
Thanks for your efforts

**Comment by adamroyjones** [comment] 2023-08-31 08:28
I see that 3.0 has been released with full support for Debian Bookworm—thanks!

And thanks, more generally, for the time and effort you put into this project.

**Comment by ploum** [comment] 2023-09-17 23:22
I believe that this bug can be closed because:

- Debian bookworm support is working really great
- Debian testing is a moving target and thus will never be fully supported

Is there a reason to keep this bug open?

**Closed** 2023-09-17 23:36 UTC
Labels: enhancement, distro-support
