### ISSUE TITLE
Wallpaper bugged after changing multi monitor display configuration

### ISSUE THREAD

**Issue by cafeoh** [regolith-linux/regolith-desktop#83] opened 2019-08-09 07:09 UTC
Hey,

Sorry if this issue is completely unrelated to Regolith, but I don't know where else to post it. When switching from mirror to extended display, my wallpaper on my primary monitor (right side, laptop) gets weirdly stretched. 

![screenshot](https://i.imgur.com/k0pLf6M.png)

This is temporarily fixed by opening `arandr`, moving the primary monitor about, applying, moving it back to it's proper location and applying again. This is a visual bug only, and doesn't really affect the logic of multimonitor setups at all, afaik it's unrelated to the earlier issues with desktop indexing and whatnot

I'm on Ubuntu 18.04.1, and this was happening on a fresh install of ubuntu + regolith aswell, with the default wallpaper.

(By the way loving the new .Xresources theme consolidation Ken!)

**Comment by kgilmer** [comment] 2019-08-09 14:49
Hi @cafeoh , yep this is an issue I believe with gnome-flashback.  In the early days, wallpaper was managed w/ `feh` and some scripts so it would refresh on monitor changes automatically.  People preferred to manage their wallpaper via gnome settings and so this is a regression.  

I have done a few searches, trying to determine if there is an automatic fix for this issue but haven't found anything.  I think unless something surfaces I'll need to re-add the logic in `xeventbind` to reset the gnome-flashback wallpaper upon any display change event, via `gsettings`.

Thanks for the feedback on Xresources @cafeoh !  It was a lot of work, glad you find it useful.

**Comment by kgilmer** [comment] 2019-08-09 14:50
BTW, nice color theme!

**Comment by cafeoh** [comment] 2019-08-09 14:59
I see, thanks for the heads-up!
Since I'm using scripts to mirror/extend my screen anyway (and for posterity) do you know what minimal `gsettings` command would force a refresh?

Thanks, didn't have to do much for scheme except set the terminal and GTK scheme, thanks to your changes! :)

**Comment by kgilmer** [comment] 2019-08-09 15:09
Yes, this is the command Regolith runs to set the wallpaper: https://github.com/regolith-linux/regolith-scripts/blob/master/regolith-config-init.sh#L70

**Comment by cafeoh** [comment] 2019-08-09 15:28
I've tried that before, but it doesn't look like it's working (doesn't look like it's changing my wallpaper either, even if I choose another one).

```gsettings set org.gnome.desktop.background picture-uri "/home/cafe/Pictures/gruvwp1.jpg"```
```gsettings set org.gnome.desktop.background picture-uri "file:///home/cafe/Pictures/gruvwp1.jpg"```
```gsettings set org.gnome.desktop.background picture-uri `xrescat gnome.wallpaper.uri "file:///usr/share/backgrounds/ESP_020528_1750_desktop.jpg"```
None of these seem to do anything, but even gnome-tweaks looks like it can't change my wallpaper... 

Problem survived a reboot, but it's probably not even related to the issue. I'll close this issue and have to take a look at it later.

Thanks!

**Comment by kgilmer** [comment] 2019-08-10 16:18
Hmm, yeah seems like something other than gnome is managing the wallpaper.  Maybe `feh` is still in your i3 config?

**Comment by waltsims** [comment] 2019-08-13 10:56
> Hmm, yeah seems like something other than gnome is managing the wallpaper. Maybe `feh` is still in your i3 config?

I'm having the same issue. I guess I installed before the move away from feh because it is still in my .i3 config. What is the recommended way to "upgrade"?

**Comment by kgilmer** [comment] 2019-08-23 03:15
Hi @waltsims , sorry I missed this.  Once updating via apt or the software program, you should compare your i3 config file in `~./config/regolith/i3/config` to `/etc/regolith/i3/config`.  If you do not have the former then Regolith is using the latter.

**Comment by kgilmer** [comment] 2019-08-23 03:16
This issue still exists, reopening.

**Comment by kgilmer** [comment] 2019-08-29 05:54
Related: https://gitlab.gnome.org/GNOME/gnome-flashback/issues/23

**Closed** 2019-09-07 04:07 UTC

**Comment by gnzlbg** [comment] 2020-02-17 13:00
Its unclear to me how to change the wallpaper in regolith. 

I'm using the Solarized dark theme, and have added a

```
exec --no-startup-id feh --bg-fill
```

to my `~/.config/regolith/i3/config`, but the wall paper gets "corrupted" and or changed back to the original one when I add external monitors. 

With external monitors, even the original wall paper gets messed up, but that seems related to #133

**Comment by kgilmer** [comment] 2020-02-17 15:50
Hi @gnzlbg , the expected way to configure wallpaper is via `Settings` (`gnome-control-center`), or [via Xresources](https://github.com/regolith-linux/regolith-styles/blob/master/Xresources/gnome#L4) by setting `gnome.wallpaper` to the absolute path of your image.  However, the latter approach is undergoing some enhancements at the moment so it's suggested to use the gnome GUI for this until R1.3.1.  If you're still having trouble w/ wallpaper by only using `Settings`, kindly open a new issue and we'll take a look. :smile:

**Comment by gnzlbg** [comment] 2020-02-17 16:44
That worked for me, thank you. Might be good to document this somewhere in the customization section of the webpage. It was not clear to me which parts of the configuration are done through the usual i3 methods, and which parts follow the usual Ubuntu / GNOME methods. Thank you for all your help!

**Comment by fadli0029** [comment] 2024-01-12 19:19
You have to edit Xresources, here's mine **(I'm using Regolith 3 Release):**

```
! Find more possible i3 overrides here:
! https://github.com/regolith-linux/regolith-wm-config/tree/main/usr/share/regolith/i3/config.d
! First check if the file already exists in your computer. For example, say
! you want a new notification daemon you found on github, you'll need to maybe work with 82_rofication.
! Check if it exist in your computer at /usr/share/regolith/i3/config.d/
! If not, copy the 82_rofication file from the github repo link above and paste it there.
! Then got to ~/.config/regolith3/Xresources (i.e: this file) and overrides the variables of interests.
! In this example, that'd be: wm.binding.notification_ui

!!!! DO NOT ADD KEYBINDS HERE. THIS FILE IS TO MODIFY VALUES/KEYBINDS, not add new ones. It's a bad practice to do so.
! To add new keybinds, got to ~/.config/regolith3/i3/config.d/my_keybinds and add your keybinds to
! something.

! Set compositor to picom
wm.program.compositor: /usr/local/bin/picom
wm.client.focused.color.border: #ff0000

wm.gaps.inner.size: 15

wm.window.border.size: 0
wm.floatingwindow.border.size: 0
wm.gaps.smart: false

! regolith.wallpaper.options is for zoom, spanned, centered, etc. (see more options from gnome tweaks -> Appearance -> Background
regolith.wallpaper.file: ~/.config/wallpapers/pastel_clouds.png
regolith.wallpaper.options: spanned

regolith.lockscreen.wallpaper.file: ~/.config/wallpapers/pastel_clouds.png
regolith.lockscreen.wallpaper.options: spanned

! Override regolith rofi config
rofi.theme: ~/.config/rofi/config.rasi
wm.program.launcher.app: rofi -show drun -theme ~/.config/rofi/config.rasi
wm.program.launcher.cmd: rofi -show run -theme ~/.config/rofi/config.rasi
wm.program.launcher.window: rofi -show window -theme ~/.config/rofi/config.rasi
wm.program.file_search: rofi -show find -modi find:~/.config/rofi/scripts/finder.sh
wm.program.look_selector: rofi -show look -modi look:~/.config/rofi/scripts/look-selector.sh
regolith.look.path: /usr/share/regolith-look/lascaille

! Override some important keybinds (see: /usr/share/regolith/i3/config.d/60_config_keybindings
wm.program.settings: gnome-control-center
wm.program.wifi: ~/.config/rofi/scripts/rofi-wifi-menu.sh
wm.program.bluetooth: ~/.config/rofi/scripts/rofi-bluetooth.sh
```
