### ISSUE TITLE
Fresh install: Super+Enter does not launch a terminal

### ISSUE THREAD

**Issue by amireldor** [regolith-linux/regolith-desktop#49] opened 2019-06-21 16:21 UTC
I'm not sure what I'm doing. I've just installed a fresh install and the terminal won't launch.  This also happened when I installed regolith-desktop from the PPA over my old Ubuntu on this laptop. Super+Shift+Enter does launch the browser however.

I tried i3-sensible-terminal which also doesn't do anything (from the Super+Shift+Space menu).

It's worth noting that the cursor does change to a "thinking" state but nothing more. No terminal. Sadness overwhelms me.

Changing to gnome-terminal in the i3-regolith config works. I guess this "st" of yours is not installed by default?

**Comment by kgilmer** [comment] 2019-06-21 18:34
Don't be sad @amireldor , we will figure it out!  From the gnome-terminal, what do you see after typing `file /usr/bin/st` ?  Did you install from the LiveCD?  Which version?

**Comment by amireldor** [comment] 2019-06-22 12:29
```
➜  ~ file /usr/bin/st
/usr/bin/st: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=7636fd36961b574ca20bc0e067143064585bc405, stripped
➜  ~ /usr/bin/st
XOpenIM failed. Could not open input device.
➜  ~ 
```
This is from my second laptop, installed with the `regolith-deskop` package. Same symptoms when hitting Super+Enter (no terminal, needed manually change to gnome-terminal). Originally an Ubuntu too. 18.04. The first laptop was installed with the Release 1.1 LiveCD. Thanks for the cool project!

**Comment by im7FFY** [comment] 2019-06-23 07:10
Have you changed your shell? I did experienced that but this was my fault, as when I installed zsh / oh my zsh they asked if I wanted to make it my default shell which I said yes, later I uninstalled zsh for whatever reason and at this point st wasn't working anymore cause of the fact that it could not find zsh, as a result when I was pressing mod+return, I could see the term window for like less than half a second then it crashed. I finally reinstalled zsh and now everything is working great. So if you did you might want to tell your system what's your shell.

**Comment by kgilmer** [comment] 2019-06-23 14:23
Also have a look at [this issue](https://unix.stackexchange.com/questions/518567/suckless-utilities-give-xopenim-failed-error/518572).  If you set LC_CTYPE does that change anything?

**Comment by kgilmer** [comment] 2019-07-01 02:34
Closing tomorrow if no response.

**Comment by amireldor** [comment] 2019-07-01 08:00
Hello, sorry for being non responsive. I do use zsh which was installed and
set to default shell previously to installing regolith-desktop. Hmm, and on
the freshly installed machine it was installed after, obviously, as
regolith was installed from a liveusb.

Again sorry for responsiveness, I can't seem to be attentive to this ATM.
Will do my best to try the LC_ thing.

**Comment by kgilmer** [comment] 2019-07-01 14:28
No problem, take your time @amireldor :smile:  

It's hard to know what to suggest to fix your issue.  If you could work from a fresh install and go slowly with customization, changing one thing at a time and verify it doesn't break anything before making the next change is a way of isolating problems that happen when setting up a new system.

**Comment by kgilmer** [comment] 2019-08-18 05:06
Assuming this was resolved or abandoned.  Closing.

**Closed by kgilmer** 2019-08-18 05:06 UTC

**Comment by amireldor** [comment] 2020-04-13 20:13
Hi, it's me again :)
It's been a while, and a few distros, and now I installed Regolith 1.3.something on a new laptop and darn, $mod+enter won't open a new terminal. I opened gnome-terminal manually with $mod+shift+space and then I tried:

> Also have a look at [this issue](https://unix.stackexchange.com/questions/518567/suckless-utilities-give-xopenim-failed-error/518572). If you set LC_CTYPE does that change anything?

And it works! The only thing I did different from this friend is that I put the export in `~/.profile` as it seems that you need this variable session-wide.

I chose US English as my language during install, but my timezone and locale is set to Asia/Jerusalem and Hebrew formats. Maybe something along that route makes LC_CTYPE confused on new installs. Is there any way I can help with this so it won't happen to future users? Thanks and sorry for resurrecting issues (but it's essentially the same issue).

**Comment by kgilmer** [comment] 2020-04-13 22:27
Hi @amireldor , thanks for the details of your issue and solution :smile: .  Did you install Regolith via PPA or ISO?  If PPA, what version of Ubuntu did you start with?

**Comment by amireldor** [comment] 2020-04-14 05:09
I installed Regolith from ISO and overridden a previous Linux on my machine. And also for completeness, the locale I chose for LC_CTYPE was 'en_US.UTF-8' which is slightly different than the one the guy on the link mentioned chose.

**Comment by kgilmer** [comment] 2020-04-14 15:47
I will try and reproduce the issue.  Was it Ubuntu 18.04 or 19.10?

**Comment by amireldor** [comment] 2020-04-14 16:52
19.10

**Comment by kgilmer** [comment] 2020-04-15 00:24
The good news: I am able to repro the issue.  It's surprising to me that specifying a different location on the map would result in the terminal not working.  
The bad news: I do not see a path forward for an easy fix.  There is a rather nasty thread on the st mailing list regarding the issue from many years back.  The developers pin the issue on something in X, not st.  So, other than what you've found (specifying LC_CTYPE), I'm not aware of another solution.  The best that occurs to me at the moment is to document the issue on the website for others that may have the same issue.  

Please let me know @amireldor if you have any other suggestions, and thanks for bringing the issue up.

**Comment by kgilmer** [comment] 2020-04-19 23:08
Just FYI @amireldor, we will move to gnome-terminal for Regolith R1.4.  There were more problems than this, but this is the most serious and because there is no easy way for me to resolve, I'd rather go with gnome-terminal than have people in various regions of the world have a poor experience with Regolith.

**Comment by amireldor** [comment] 2020-04-20 07:03
Cool! Thanks for letting me know. I ended up with gnome-terminal as default
myself.
