### ISSUE TITLE
Overlapping of Windows

### ISSUE THREAD

**Issue by Xacrolyte** [regolith-linux/regolith-desktop#35] opened 2019-06-17 07:44 UTC
The basic tiling process isn't executing properly. Specifically, when I run image and video captures via a python executable; it causes them to stack up one on top of another and eventually freezes.

**Comment by kgilmer** [comment] 2019-06-17 14:27
Hi @Xacrolyte , is there a way I can reproduce what you're experiencing?  I have not seen the behavior you describe.

**Comment by Xacrolyte** [comment] 2019-06-18 06:54
I believe that using opencv, tensorflow, or any subsequent library for video processing and projecting them to open multiple windows with image/video captures will give you the above mentioned behavior.

**Comment by kgilmer** [comment] 2019-06-20 03:37
Unfortunately I'm not familiar with any of these tools.  Have you used this setup with other i3 environments?  [This was the top search result](https://www.reddit.com/r/i3wm/comments/7h3lpo/display_name_of_floating_window/) for "i3 opencv" so I'm guessing this is a general issue of i3.  Perhaps the fix listed there will help.  Since this isn't an issue of Regolith itself I will close it.

**Closed by kgilmer** 2019-06-20 03:37 UTC
