### ISSUE TITLE
No system tray even after following instructions

### ISSUE THREAD

**Issue by roadriverrail** [regolith-linux/regolith-desktop#181] opened 2019-12-26 15:30 UTC
Hey, y'all!  I've been in love with Regolith for months, except for one small problem.  I've followed your documentation and absolutely cannot make the system tray appear!  When I launch something like nm-applet, I see no indications from i3bar that there was ever a docking attempt made, and I've tried every debugging step I can think of and I'm at my wit's end.  To save time, I'll go ahead and attach my config file, an i3bar debug log from the last time I tried to load nm-applet, and here's a snippet from my xrandr output that seems to indicate I do have a primary display:
`HDMI-0 connected primary 3840x2160+7680+0 (normal left inverted right x axis y axis) 600mm x 340mm`

What other steps have I not considered?
[configandlog.zip](https://github.com/regolith-linux/regolith-desktop/files/4002866/configandlog.zip)

**Comment by kgilmer** [comment] 2019-12-27 01:29
Sanity test of setting `tray_output primary` and running `nm-applet`: 
![image](https://user-images.githubusercontent.com/49683/71495926-32c5e900-2805-11ea-9be8-949b160a0931.png)

**Comment by kgilmer** [comment] 2019-12-27 01:35
Also, FWIW, your i3bar log file is empty but I wouldn't expect there to be anything actionable in there anyway.

**Comment by roadriverrail** [comment] 2019-12-27 18:52
I should mention that I also run Slack and definitely don't have that logo in the tray either.  This is actually happening on two different machines for me, too...both my desktop and laptop.

Apologies for the empty log.  I did tail it to my console and have output at one point.  I was looking for evidence that apps were trying to dock to i3bar.  I didn't see any sign of that at all.  I'm no slouch but I'm not super familiar with X so I just don't know how to troubleshoot farther.  Is it possible there's some other dock process out there that all the apps are trying to dock to?  Maybe they're trying to dock to a nonexistent process?  I'm really seeking out troubleshooting steps here.

**Comment by kgilmer** [comment] 2019-12-28 01:45
It's certainly possible that some other component is stealing the tray icons.  I also confess to not knowing too much about how these tray applets work.  I'm assuming you installed Regolith via PPA and not the LiveCD installer.  Perhaps there are some Xsession, bashrc, or other configuration files you have that are launching something that is stealing the tray icons.  There is at least [one issue](https://askubuntu.com/questions/449658/networkmanager-tray-nm-applet-is-gone-after-upgrade-to-14-04-trusty) that seems to relate to other Destkop Environments having issues with the tray.

**Comment by roadriverrail** [comment] 2019-12-30 15:20
I've done hours of hunting at this point and I cannot find any indication of some other component stealing tray interactions.  I don't have an Xsession file in my home directory, and my .bashrc doesn't appear to have anything relevant.

However, I have reproduced this on a **third** machine, as I use Regolith Desktop at work as well.  This is a third machine where Regolith was installed via the PPA rather than from a fresh install, so there's definitely a connection here.  Like, is there perhaps a package missing from the dependencies that ought to be there?  The machines are all slightly different (one was on KDE Plasma before going to Regolith and my removal of all KDE packages, two were on Unity...all slightly different Linux distros...one's a 3-screen desktop, one's a one-screen desktop, one's a laptop...), but do have the common factor of getting Regolith Desktop from PPA.

**Comment by roadriverrail** [comment] 2019-12-31 16:56
Alright...I have a root cause for you!  The tray icons are being stolen by something from GNOME called "indicator" which is launched by `/etc/xdg/autostart/indicator-application.desktop` and `/etc/xdg/autostart/indicator-messages.desktop`.  Just doing `ps -ef | grep indicator` and killing the listed processes is enough to restore the i3 tray!

As a hacky fix, I did `cp /etc/xdg/autostart/indicator* /etc/xdg/xdg-regolith/autostart` and then edited each `.desktop` file to change `NoDisplay=false`.  From there, I could start the "Startup Applications" app and uncheck them from the list, which means they'll stop running automatically.

I suspect there's a more elegant way to provide alternate `.desktop` files and put them in the reolith autostart directory so that XDG looks at them and then, somehow, chooses not to autostart them.  Thoughts?

**Comment by kgilmer** [comment] 2020-01-05 16:56
Hi @roadriverrail , thanks for the details!  From your findings it does look related to the ongoing work in gnome-flashback I was discussing with another dev.  Another user has reported a similar issue in our slack channel and was able to resolve it by uninstalling `indicator-application`. I'm not sure if this is something that would work for you but if you're able to experiment it would be good to know if this is a simple(er) general fix to the issue...

https://regolith-linux.slack.com/archives/CLYDASBFS/p1578242981104200?thread_ts=1577479032.043500&cid=CLYDASBFS

`sudo apt remove indicator-application`

**Comment by fhchl** [comment] 2020-01-07 15:51
Killing the indicator process also gave me the trays back!

**Comment by roadriverrail** [comment] 2020-01-07 15:55
@kgilmer Using the method I indicated above did represent a fix for me.  What I'd like to do at this point is be part of the solution going forward.  Could the `regolith-desktop` PPA install some files in `/etc/xdg/xdg-regolith/autostart` that would override any existing ones?  Is there a way to specify "no, do  *not* autostart this" in a `.desktop` file?

**Comment by kgilmer** [comment] 2020-01-09 18:33
Great, would love your help!  Packages cannot overwrite files provided by another package unless said package conflicts/replaces the existing package.

What is the file you'd like to override?

Another option would be to declare a conflict against indicator-application from regolith-desktop. This assumes that removing that package is not detrimental to other DEs which seems like it may be.

**Comment by roadriverrail** [comment] 2020-01-09 18:53
Basically, what I'd be arguing for is:

- The package creates the files `/etc/xdg/xdg-regolith/autostart/indicator-application.desktop` and `...indicator-messages.desktop`
- The contents of these files should be a copy of the ones you can find under `/etc/xdg/autostart` on a standard Ubuntu machine with the following line added to them: `X-GNOME-Autostart-enabled=false`

Based on my pretty ignorant reading of `.desktop` files, the autostart mechananism, and the way regolith prioritizes its xdg config dirs over the standard ones, this should lead to  the indicator apps being turned off by default in Regolith, so people installing via the PPA will get their tray from the start.

**Comment by karlsebal** [comment] 2020-01-30 10:59
For me it is sufficient to disable `indicator-application.desktop` by adding the line mentioned.

**Comment by chrisynl** [comment] 2020-03-18 01:27
Adding `X-GNOME-Autostart-enabled=false` to the `/etc/xdg/xdg-regolith/autostart/indicator-application.desktop` and `...indicator-messages.desktop` can fix this.

**Comment by kgilmer** [comment] 2020-03-24 02:09
I do not have these files on my computer.  Still trying to root-cause this issue.  I cannot reproduce as-is after enabling the tray and using slack.  I did not have `indicator-application' installed, nor did I have `obession` package installed.  Can anyone verify what Ubuntu variant they are running on?  Stock Ubuntu+Regolith PPA?  Regolith Installer?  Some other variant + Regolith PPA?

I believe that uninstalling the [package `obsession`](https://packages.ubuntu.com/bionic/obsession) [should prevent](http://manpages.ubuntu.com/manpages/xenial/man1/xdg-autostart.1.html) this situation from occuring, however since I cannot test and do not know why others have these packages installed, cannot say at all if this will break other things.

**Comment by roadriverrail** [comment] 2020-03-24 03:45
@kgilmer I can only speak for myself, but I generally use vanilla Ubuntu with the Regolith PPA.  I do not have the package `obsession` installed and have never even heard of it.

**Comment by karlsebal** [comment] 2020-03-24 07:05
@kgilmer `obsession` is not installed. Regolith was brought to the machine via PPA. 

On the machine I did not have the indicator problem `indicator-application.desktop` is not present in `/etc/xdg/autostart` which is puzzling because `indicator-application` is installed on both.

Package installing those files however are `indicator-application` and `indicator-messages`.

**Comment by karlsebal** [comment] 2020-03-24 07:16
Maybe this is not regolith related but a problem with the underlying Ubuntu. I never checked if icons are displayed properly when running Unity session.

https://askubuntu.com/questions/1030833/app-indicators-not-working-on-ubuntu-18-04
https://www.linuxuprising.com/2018/12/fix-missing-indicator-icons-in-ubuntu.html

**Comment by chrisynl** [comment] 2020-03-30 05:30
@kgilmer I am using Ubuntu 18.04, I install regolith-desktop via PPA, and I think it maybe something wrong with gnome when using regolith. When I remove regolith and install i3, the tray icons can show in i3-bar. So if just using i3, the tray icons work normally, but if using regolith, something steals tray icons.

**Comment by RafalSkolasinski** [comment] 2020-03-30 17:20
I hit the same problem and savagely removed `/etc/xdg/autostart/indicator-application.desktop` ; - )

**Comment by alexzaizar09** [comment] 2020-05-07 21:58
Hi, i have just installed Pop OS 20.04 and immediately install regolith desktop. Everything is working except for the i3x status icons. None is being shown. I have tried uninstalling the indicator but it is not even installed. What can i do?

**Comment by kgilmer** [comment] 2020-05-08 03:17
Did you install the i3xrocks packages as described here @alexzaizar09 ?  sudo apt install i3xrocks-net-traffic i3xrocks-cpu-usage i3xrocks-time

If so, please try to run `i3xrocks -u ~/.config/regolith/i3xrocks/conf.d -d /etc/regolith/i3xrocks/conf.d` from a terminal and respond with the output you get.

**Comment by alexzaizar09** [comment] 2020-05-12 01:59
sorry i was trying  to make it work.  Yes i have uninstalled them and reinstall them also an nothing is showing? i have follow all the setup from your web page

**Comment by roadriverrail** [comment] 2020-05-12 02:27
@alexzaizar09 If it's not too much to ask, could you start a new issue for your problem?  This issue is for a problem with the system tray and dock and is really only open until someone implements the solution.

**Comment by alexzaizar09** [comment] 2020-05-12 02:35
sorry i wouldn't mind but i have decided to hop into arcolinux, looks easier to learn a new package manager than finding and resolving conflicts, anyway thank you

**Comment by moritzheiber** [comment] 2020-05-27 08:58
Just for future reference: You can also copy the `indicator-application.desktop` file to `~/.config/autostart/` and change it at will without having to touch anything in `/etc` or overwriting existing files. Your problems will return on the next update to `indicator-application`.

The right way to solve this would be to just uninstall `indicator-application`. Seeing as `regolith-systems` already conflicts with it I would say that's a good way forward.

_Note: `indicator-application` still appears to be a dependency of `ubuntu-mate-core`, which means if you're running this off the Regolith PPA on Ubuntu MATE you will have to use the workaround of copying the `.desktop` file and disabling it manually by adding `X-GNOME-Autostart-enabled=false` to its content.

**Comment by alexzaizar09** [comment] 2020-05-27 14:03
Thanks, that could be helpful unfortunately i'm not in using ubuntu
anymore. But if i distrohop back to it i will definitely install regolith
you and your peers have made a great distro.

**Comment by roadriverrail** [comment] 2020-05-27 15:43
@moritzheiber So, let's just say for the sake of argument we were trying to make this entire thing turnkey for someone who was doing a PPA install from standard Ubuntu.  I've done this on three different pieces of hardware so far and this scenario describes every colleague I've also turned on to Regolith.  Is there any way possible to make the PPA install do these steps (I know nothing about what packages can and can't do)?  If not, is there a way to make a note about this in the install instructions for Ubuntu users?  I think if we could at least prevent others from stepping on this booby trap, it'd be a good resolution.

**Comment by kgilmer** [comment] 2020-05-28 01:23
There is this line between the system and the user.  Packages do not make modifications to user directories, only update the system itself.  The reason I cannot see a way of automating this cleanly is that as @moritzheiber mentions MATE (and others it looks like such as Budgie) use this package.  So a user with MATE installed, trying Budgie, would have a package uninstalled in the background and then be puzzled as to why there system behavior changed.

We are working on a intro UI that will give new users some information and allow them to make some user changes.  This may be a place where we could check for the existence of the package in question and present some options to the user.  Because this UI will be running in the user's context, it would have the ability to write files in the users config.

 In the short term, these troubleshooting steps can be added to the website.

**Comment by kgilmer** [comment] 2020-05-28 01:24
Also, thanks for recommending Regolith to your colleagues @roadriverrail !  FWIW the ISO version does not have this issue due to it's monolithic nature.

**Comment by roadriverrail** [comment] 2020-05-28 01:48
No doubt.  PPA just happens to be more common because our IT department will give us vanilla Ubuntu after they add their device management secret sauce.  So, getting the ISO version validated isn't going to happen, but I and some others PPA in Regolith first thing after.

I'll leave the issue open so as to help remind for a documentation update, bit otherwise, you're welcome to close it at will.  Thank you for the thorough attention.

**Closed** 2021-01-02 14:47 UTC
Labels: configuration

**Comment by newptcai** [comment] 2024-09-30 07:04
I got this problem again on Regolith 3.2 after upgrading to Ubuntu 24.04.1. It has been fixed by removing `indicator-application` via
```
sudo apt remove indicator-application
```

I hope this can be fixed permanently!
