### ISSUE TITLE
Doesn't start on Ubuntu 19.10

### ISSUE THREAD

**Issue by rkononov** [regolith-linux/regolith-desktop#105] opened 2019-08-31 18:38 UTC
Seems like something was broken during most recent upgrades (I suspect ubuntu/gnome).
Doesn't start at all - just gray screen, nothing works (shortcuts or something).
Gnome works without issues.
I even removed completely, cleaned out all the files and reinstalled from scratch and the same.
Any ideas how to debug/which logs to check?(if I replace Exec=i3-gnome-flashback-session with just i3 it loads)

**Comment by kgilmer** [comment] 2019-09-01 16:25
HI @rkononov , how did you install Regolith on Ubuntu 19.10?  Since I don't distribute packages for that version I'm guessing you did an upgrade from an earlier Ubuntu version.  For troubleshooting, check `/var/log/syslog` for messages from i3, gnome, or regolith during the timeframe that your login attempt occurs.

**Comment by rkononov** [comment] 2019-09-01 16:27
Thanks I'll check syslog (yep I upgraded from the previous one)

**Comment by rkononov** [comment] 2019-09-01 16:52
I found the only CIRITAL message in the logs around the i3 start time (below)
Is there anything I could try else - maybe build from sources?

```
Sep  1 19:42:05 norn-XPS-15-9560 gnome-session[9550]: gnome-session-binary[9550]: WARNING: Unable to find required component 'org.gnome.SettingsDaemon.Clipboard'
Sep  1 19:42:05 norn-XPS-15-9560 gnome-session-binary[9550]: WARNING: Unable to find required component 'org.gnome.SettingsDaemon.Clipboard'
Sep  1 19:42:05 norn-XPS-15-9560 gnome-session[9550]: gnome-session-binary[9550]: WARNING: Unable to find required component 'org.gnome.SettingsDaemon.Mouse'
Sep  1 19:42:05 norn-XPS-15-9560 gnome-session-binary[9550]: WARNING: Unable to find required component 'org.gnome.SettingsDaemon.Mouse'
Sep  1 19:42:05 norn-XPS-15-9560 gnome-session[9550]: gnome-session-binary[9550]: WARNING: Unable to find required component 'gnome-flashback-init'
Sep  1 19:42:05 norn-XPS-15-9560 gnome-session-binary[9550]: WARNING: Unable to find required component 'gnome-flashback-init'
Sep  1 19:42:05 norn-XPS-15-9560 gnome-session[9550]: gnome-session-binary[9550]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Sep  1 19:42:05 norn-XPS-15-9560 gnome-session-binary[9550]: CRITICAL: We failed, but the fail whale is dead. Sorry....
```

**Comment by kgilmer** [comment] 2019-09-01 17:02
Thanks for providing the log details @rkononov .  It may be something with `gnome-session`.  There is nothing here that provides me enough information to provide a fix or suggest more troubleshooting steps.  I plan to support 19.10 but will probably not be able to focus on this in the short-term.

**Comment by rkononov** [comment] 2019-09-01 17:34
@kgilmer anything I could do for debugging?(any way to launch this binary in debug mode  or increase log level) - I have some development experience and really interested in fixing this, but no idea what to start with

**Comment by kgilmer** [comment] 2019-09-01 23:15
The script that runs to launch i3 is `/usr/bin/i3-gnome-flashback`.  This gets executed upon login.  Perhaps by adding debug statements in that script when you try and start it up we can find out where in the script (assuming the problem is in there) the problem lies...

**Comment by kgilmer** [comment] 2019-09-15 02:52
WIP: 
![regolith-eoan](https://user-images.githubusercontent.com/49683/64916008-325b8380-d729-11e9-81c6-fa86f1e96c1f.png)

**Comment by kgilmer** [comment] 2019-09-15 14:38
This change is now available for testing in the `regolith-unstable` PPA.

**Comment by rkononov** [comment] 2019-09-15 17:32
Thanks!
I'll test it right away (btw had a chance to debug it and it was failing on gnome-session start, unfortunately even in debug mode it was not so informative)

**Comment by rkononov** [comment] 2019-09-15 17:52
Thanks it's fixed!
Could you point to the commit with the fix?(out of curiosity)

**Comment by kgilmer** [comment] 2019-09-16 03:19
Yay, glad to hear it @rkononov :smile: .  Regarding the fix, I basically just installed it on a laptop and tried changing things until I could get it to work.  I found some commits in gnome-flashback related to some of the warnings I was seeing when the session was trying to start.  However it was pretty difficult to determine exactly what was wrong, and so had to resort to trial and error.  Here's eventually what I reduced the changes down to: https://github.com/regolith-linux/regolith-gnome-flashback/commit/151d7d671df79957abc521d5326dd38559c32a1f

**Comment by leosunmo** [comment] 2019-10-08 20:30
As this seems fixed for now I'll close this ticket. Please open a new one if there's any further issues on 19.10! I'm sure we'll encounter some new ones as we keep developing Regolith.

**Closed by leosunmo** 2019-10-08 20:30 UTC
