### ISSUE TITLE
multiple monitors

### ISSUE THREAD

**Issue by WuerfelDev** [regolith-linux/regolith-desktop#12] opened 2019-04-24 23:13 UTC
i booted live with my monitors plugged in, ordered the screens in settings. After that the wallpapers are this: (it doesn't fit per monitor)
![Screenshot from 2019-04-24 22-47-36](https://user-images.githubusercontent.com/12686819/56699577-a0a19a00-66e5-11e9-8449-872a4f4a16d0.png)
I logged out (Super+E), unplugged both monitors, logged in and then i hot plugged the monitors (put the laptop into the docking station) and the wallpaper is stretched somehow:
![Screenshot from 2019-04-24 22-48-38](https://user-images.githubusercontent.com/12686819/56699673-055cf480-66e6-11e9-98b1-a71245a64842.png)

The system doesn't handle the monitors right, see how they are numbered
![Screenshot from 2019-04-24 23-10-13](https://user-images.githubusercontent.com/12686819/56699781-756b7a80-66e6-11e9-8f3f-9081f3ed9c0e.png)
I think this could be the cause for the problems above

**Comment by kgilmer** [comment] 2019-04-25 02:42
Thanks for the screenshots @WuerfelDev , very helpful.  Looks like there are two issues:
- wallpaper distorted or stretched when using multiple monitors
- gnome settings desktop indexing inconsistent

The first one can be worked around with super-shift-r.  This reloads i3 which causes feh to refresh the wallpapers w/ the current screen configuration.  To fix this the right way, either wallpaper must be fully managed by gnome-shell or an event hook of some kind has to cause feh to execute with each monitor hotplug event.  I'll look into it.

The second issue is new to me.  I don't have two external monitors on hand to test this but maybe I can reproduce it with two.

Thanks again for reporting the issue.

**Comment by mochja** [comment] 2019-04-25 11:41
I do have same issue with external monitors. Numbering is incorrect and I am not able to put them in right position, they always renumber. I am able to order them correctly via ARanrR.
One monitor is connected via HDMI, other one is DP and 3rd one is daisy chained from 2nd.

**Comment by kgilmer** [comment] 2019-04-27 22:07
I will work on a fix for the wallpaper issue, from searching should be pretty straightforward. 

Regarding the monitor index issue, I notice some fixes have been made in gnome-control-center around this ([see here](https://gitlab.gnome.org/GNOME/gnome-control-center/blob/master/NEWS)).  Next week I should get access to multiple monitors so can reproduce the issue and see if a newer version of gnome-control-center resolves them.

**Comment by kgilmer** [comment] 2019-05-06 04:27
I am testing a program, xeventbind that should deal w/ the wallpaper corruption issue.  Regarding the monitor index issue, I can see this even with two monitors.  I will try a newer version of `gnome-control-center` when testing newer versions of Ubuntu next week.

**Comment by kgilmer** [comment] 2019-05-09 14:37
Still testing xeventbind.  The timing of wallpaper refresh needs consideration as the display framebuffers are created and destroyed during hotplug events.

Regarding the display index bug, I've given up on trying to backport `gnome-control-center` from Disco to Bionic.  The dependency tree is large and a transitive dependency `gnome-settings-daemon` seems to require build tool versions not available in pbuilder.  It isn't clear to me how I would satisfy the build dependencies.  

I think the best approach going forward is for those wishing for fixes to `gnome-control-center` should simply install Regolith on an existing Disco install.  If there is desire I can provide a livecd installer based on Disco instead of Bionic at some point in the future.  

The Disco versions of Regolith are only available in the `regolith-unstable` package for now.  There have been some serious bugs reported and want to get those ironed out before promoting to the stable PPA.

**Comment by kgilmer** [comment] 2019-05-13 14:26
The wallpaper refresh issue fix is available in `regolith-unstable` for testing on Bionic via the `regolith-xeventbind` package.  There are a few of other changes ,the main one being keybinding changes for vim-style window navigation and to allow for faster control panel access for common functions such as select wifi network [super+w] and bluethooth [super+b].  The conky shortcuts have been updated with the new sequences but the web docs will need to be updated before pushing to `regolith-stable`.  

Would love any feedback on the xeventbind wall paper fix and/or the key bindings changes!

**Comment by kgilmer** [comment] 2019-05-15 15:04
I haven't noticed any regressions with the wallpaper refresh fix on my work computer (where I am using multiple monitors).  I'll give it a few more days if anyone else would like to test before pushing the updates to `regolith-stable`.

**Comment by kgilmer** [comment] 2019-05-18 16:28
I will push the updates to `regolith-stable` today.  I used the wallpaper refresh fix for a week without any problems.

**Comment by kgilmer** [comment] 2019-05-21 03:10
I'm closing this assuming it's fixed.  I am now using 3 monitors at work w/ Regolith on Ubuntu 18.04 and do not have any problems managing workspaces across screens or having garbage wallpaper.  Kindly reopen if there are still issues.

**Closed by kgilmer** 2019-05-21 03:10 UTC
Labels: bug

**Comment by jzelner** [comment] 2019-06-17 21:43
Is this fix in the 19.04 based Regolith district? Just tried that one off the live usb, and had this same issue. Should I try 18.04? Thanks!

**Comment by kgilmer** [comment] 2019-06-18 02:56
Hi @jzelner .  I'm assuming you're referring to the "wallpaper garbage" issue and not the "monitor index mismatch" in gnome-control-center.  I believe the update did not make it into either 18.04 or 19.04 livecd images, but if you install and then `apt update` you'll get the fix applied.
