### ISSUE TITLE
Theme not applied to Xournal++

### ISSUE THREAD

**Issue by AlessandroW** [regolith-linux/regolith-desktop#306] opened 2020-04-06 11:06 UTC
Hello,
I'm trying out Regolith and it looks really good, well done!
As I was installing Xournal++, I realized that the theme was not applied.
Interestingly, it's the only application so far that doesn't work.
On my other machine however it is (arc-theme), so I guess it's not an Xournal++ issue.
![Screenshot from 2020-04-06 13-00-42](https://user-images.githubusercontent.com/29565912/78551909-cc3e6700-7806-11ea-96e1-87d551c48aaa.png)

Steps to reproduce:
```shell
sudo add-apt-repository ppa:andreasbutti/xournalpp-master
sudo apt update
sudo apt install xournalpp
xournalpp
```
1) Can some verify this?
2) Any idea what's going on? (Xournal++ uses GTK-3, so I guess it should work)

Thanks!

**Comment by kgilmer** [comment] 2020-04-07 01:46
I've seen issues with apps installed via snap having totally different themes.  Also, can you see if another GTK theme fixes the issue?  You can easily switch gtk themes with the gnome-tweaks tool.

**Comment by AlessandroW** [comment] 2020-04-07 07:31
Interesting, the HighContrast and HighContrastInverse theme do work.
For other themes like Cahuella and Radiance the theme does change but totally differently than for the other applications. 

Now, I installed Xournalpp directly and the theme is always correctly applied. So it seems that it's snap's fault.

I guess this can be closed then. 
Thank you very much!

**Comment by farsil** [comment] 2020-04-07 13:39
I can confirm that snap does not respect system themes. It is probably because snap images package their own GTK.

**Comment by kgilmer** [comment] 2020-04-07 15:12
I will close this now as it's not an issue with Regolith itself.  There may be a way of specifying that the snap-based app has access to the system GTK themes.  I have not tested but this link looks promising: https://snapcraft.io/docs/snap-confinement

**Closed by kgilmer** 2020-04-07 15:12 UTC
