### ISSUE TITLE
Regolith doesn't save display arrangement

### ISSUE THREAD

**Issue by marcelobelli** [regolith-linux/regolith-desktop#52] opened 2019-06-24 16:51 UTC
Hi, I use my notebook with pop_os (Ubuntu 19.04 based) using two displays: One connected using thundebolt and another using HDMI. 

My problem is that every time that I log in I have to rearrange my displays.

This problem only happens with Regolith. When I log in using gnome,  my display arrangement are correct.

**Comment by arroadie** [comment] 2019-06-24 21:05
I can second this and add that when I open the gnome-control-center and go to the devices menu, it crashes with the following error

```➜  ~ gnome-control-center

(gnome-control-center:20476): display-cc-panel-WARNING **: 13:57:14.743: no sunset
data, using 16.00

(gnome-control-center:20476): display-cc-panel-WARNING **: 13:57:14.744: no sunrise data, using 8.00

(gnome-control-center:20476): GLib-GObject-CRITICAL **: 13:57:14.762: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
[1]    20476 segmentation fault (core dumped)  gnome-control-center
```

**Comment by kgilmer** [comment] 2019-06-25 04:24
@marcelobelli yes I have the same problem.  I do not know the root-cause of this issue but suspect it's related to how gnome and i3 interact when monitors are added to the system.  There may be some timing issue that causes workspaces to randomly be assigned.  While I don't know how to fix the root cause at this time I am working on a band-aid: https://github.com/regolith-linux/i3-snapshot

I have been using it for about a week experimentally.  It isn't perfect but it does help.  I map the program to i3 keybindings so i can quickly save and restore my window layouts after sleep/resume.  If you'd like to give it a shot as well I'd really value the feedback, and can provide some better documentation.  But, either way this program will make it into Regolith in the near future.

**Comment by kgilmer** [comment] 2019-06-25 04:25
@arroadie regarding your crash, can you kindly create a separate issue for this and give me some more details such as Ubuntu version, how you installed Regolith, and if you see the same crash from an Ubuntu session?

**Comment by marcelobelli** [comment] 2019-06-25 12:22
> If you'd like to give it a shot as well I'd really value the feedback, and can provide some better documentation.

@kgilmer, you can count on me!

**Comment by kgilmer** [comment] 2019-06-25 14:53
Thanks @marcelobelli :smile:   I've added notes on how to add i3-snapshot into your i3 config file in the README of i3-snapshot: https://github.com/regolith-linux/i3-snapshot

At this time I have not packaged it so to use it you'll need to compile the source.  If you'd prefer to use a debian package let me know and I'll set that up.

**Comment by kgilmer** [comment] 2019-06-28 14:41
FWIW I have to use windows at work on occasion w/ the same hw configuration and noticed it has the same issue ~ windows are placed randomly on monitors after resume.

**Comment by marcelobelli** [comment] 2019-06-28 14:51
With gnome this never happen to me :thinking: 
I did some tests yesterday. If I start with just one display, when I connect the second one the arrangement obeys gnome display configuration.

Now talking about i3-snapshot, i installed, save the configuration with the correct display arrangement, logged out and then logged in. The display arrangement was messed up. Tried to load the config but nothing changes. Did I made something wrong?

**Comment by kgilmer** [comment] 2019-06-28 15:06
Ah, i3-snapshot will not work across login sessions by default as it uses the id of X client windows to identify them.  I have not tested this use case at all but you can try telling i3-snapshot to use[ window titles](https://github.com/regolith-linux/i3-snapshot/blob/master/src/main.cpp#L179) rather than ids by adding the `-t` flag to the restore.  It would only work of your window titles have not changed (terminal titles are set to the current directory in the terminal).

If you're looking something more static, that lasts across reboots you probably would be better served with https://i3wm.org/docs/layout-saving.html.  Also I just found https://github.com/talwrii/i3-clever-layout which might also be of help, but I've only read the docs.

Let me know what you try and if you find something that works for you.

**Comment by smschauhan** [comment] 2019-08-28 06:48
Is there any progress on this one? Love Regolith, but the inability to use multiple monitors is severely off-putting.

**Comment by kgilmer** [comment] 2019-10-30 04:28
Related: https://github.com/regolith-linux/regolith-desktop/issues/159

**Comment by kgilmer** [comment] 2019-12-25 04:26
I'm closing this ticket which I see as two issues:
1. i3 workspaces being rearranged after monitor hotplug events
2. gnome issues with multi monitor setups

For #1, I do not have a fix (or even a description) for the root cause, but a utility called i3-snapshot will ship w/ R1.3 that will allow users to save and restore window layout via keybindings.  If I become aware of a precise way of isolating the issue to i3 or another component I will post a bug upstream and reference this ticket.  

For #2, I cannot repo the issue.  For those that are having issues configuring their monitors via gnome-control-center, kindly file a bug upstream here: https://gitlab.gnome.org/GNOME/gnome-control-center/issues

**Closed by kgilmer** 2019-12-25 04:26 UTC
Labels: 1.3 Target, enhancement
