### ISSUE TITLE
Bug: deactivation of touchpad doesn't work

### ISSUE THREAD

**Issue by nobodyzen** [regolith-linux/regolith-desktop#360] opened 2020-04-30 12:55 UTC
Hello

On a fresh Regolith install, deactivate the touchpad in the settings panel doesn't work. It is still possible to use the touchpad afterward.

Thanks for the great work !

**Comment by kgilmer** [comment] 2020-05-03 00:19
Created upstream issue for this: https://gitlab.gnome.org/GNOME/gnome-flashback/-/issues/54

**Comment by savaged** [comment] 2020-05-06 10:23
> Created upstream issue for this: https://gitlab.gnome.org/GNOME/gnome-flashback/-/issues/54

Looks like that issue was closed. It appears two libraries are conflicting. Perhaps one can be removed subject to testing?

**Comment by kgilmer** [comment] 2020-05-06 13:58
Hi @savaged , yes I will prepare an updated ISO (R1.4.1) without the `synaptics` package installed by default, unless we learn that it's some how needed.

**Comment by itacirgabral** [comment] 2020-05-06 14:02
I can confirm the issue at V1.4. Removing xserver-xorg-input-synaptics and restarting is enough.
```
sudo apt remove xserver-xorg-input-synaptics
```
"tap to click" and "Natural Scrolling" is working right for me now. I haven't noticed anything strange so far without synaptics.

**Comment by savaged** [comment] 2020-05-06 15:03
I'll run the removal and see if I get any symptoms over the normal course of my routine.

**Comment by kgilmer** [comment] 2020-05-12 16:31
This is now fixed in the R1.4.1 ISO release.  PPA users should not experience this issue unless for whatever reason they have the synaptics driver installed.

**Closed by kgilmer** 2020-05-12 16:31 UTC
Labels: bug, verified

**Comment by newptcai** [comment] 2021-11-15 12:41
> I can confirm the issue at V1.4. Removing xserver-xorg-input-synaptics and restarting is enough.
> 
> ```
> sudo apt remove xserver-xorg-input-synaptics
> ```
> 
> "tap to click" and "Natural Scrolling" is working right for me now. I haven't noticed anything strange so far without synaptics.

I found removing `xserver-xor-input-synaptics` make the touchpad a bit difficult to use. Is there anyway to keep this?

**Comment by kgilmer** [comment] 2021-11-15 14:19
Hi @newptcai , I haven't tested but the bug seems to indicate a conflict between the two packages,  Does your system work if you keep `xserver-xor-input-synaptics` but remove `xserver-xorg-input-libinput`?

**Comment by newptcai** [comment] 2021-11-15 15:05
No. Removing this does not have any effect. But it's OK. I can live without natural scrolling. :smile:

**Comment by seanjennings960** [comment] 2022-09-03 16:08
I noticed similar to @newptcai. Running Regolith 1.6 installed on top of Ubuntu 20.04 on an ASUS laptop.

I was trying to disable "Tap to Click," but it was not working through the Regolith settings. Removing `xserver-xor-input-synaptics` also removed touchpad functionality. For me, it disabled right-click, which wasn't viable. I ended up going through `xinput` and `synclient` to manually disable Tap to Click and edge scrolling.

Called the following script from `.xprofile` to configure it on startup (script must be called after Xserver session has started):
```bash
#!/bin/sh
set -e
DEVICE_NAME="ELAN1200:00 04F3:303E Touchpad"
# Disable Tap to click
xinput set-prop "${DEVICE_NAME}" "Synaptics Tap Action" 0
# Flip 4/5 mapping to enable natural scrolling
xinput set-button-map "${DEVICE_NAME}" 1 2 3 5 4 6 7 8 9 10 11 12
# Disable edge scroll.
synclient VertEdgeScroll=0
echo "Keyboard Configuration successful"
```
Found [this](https://wiki.archlinux.org/title/Touchpad_Synaptics#Advanced_configuration) and [this](https://www.reddit.com/r/i3wm/comments/9s53re/no_twofinger_right_click_or_taptoleftclick_in_i3/) to be helpful resources.

At last, no incidental palm clicks!! Loving Regolith by the way :smile:
