### ISSUE TITLE
Launch command cannot take parameters in Regolith 2

### ISSUE THREAD

**Issue by newptcai** [regolith-linux/regolith-desktop#731] opened 2022-09-29 01:39 UTC
When I hit `super+shift+space`, I see the Launch Command window. If I type a command like `texdoc emoji`, nothing happens. The command is not executed.

This used to work in Regolith 1

**Comment by newptcai** [comment] 2022-10-01 01:54
For the moment, I will just use `gmrun` by adding the following key bindings.
```
## Launch // Command // <Alt> F2 ##
bindsym $alt+F2 exec --no-startup-id gmrun
```

**Comment by kgilmer** [comment] 2022-10-02 17:43
This is a duplicate of https://github.com/regolith-linux/ilia/issues/3

**Closed by kgilmer** 2022-10-02 17:43 UTC
Labels: bug, needs-triage
