### ISSUE TITLE
Can't enable VPN

### ISSUE THREAD

**Issue by JohnGebbie** [regolith-linux/regolith-desktop#64] opened 2019-07-07 14:27 UTC
When I try to enable my VPN in the network settings it instantly toggles back off.

When I click its cog and go to the 'Identity' tab, the password is blank. If I fill it in click 'Apply' and go back to the tab its blank again.

If I switch over to Ubuntu (I'm using Regolith as a desktop session) I can toggle it on. It stays on even when I switch back to Regolith. But when I reboot or sleep my computer, it's gone again.

It doesn't matter too much to me, but I hope this is helpful.

**Comment by KatonaZsolt** [comment] 2019-07-07 21:48
Same issue here too.

**Comment by kgilmer** [comment] 2019-07-08 01:19
Hmm, interesting.  I don't use a VPN myself so am not really sure how I can reproduce this.  I tried creating a fake VPN and did see this "...instantly toggles back off" behavior as well.  @JohnGebbie or @KatonaZsolt  can either of you give me a snippet of your `/var/log/syslog` for when you try to enable the VPN?  To do this, open a terminal, type `tail -f /var/log/syslog`, hit enter a few times to seperate the old log data from what we want, then press the VPN toggle.  gnome-control-center will hopefully emit some error information that may provide clues.

**Comment by KatonaZsolt** [comment] 2019-07-08 09:29
Hello, tanks for the quick response! Here is my result:
...
Jul  8 11:21:28 Z-ROG-18 NetworkManager[2640]: <info>  [1562577688.9547] audit: op="connection-activate" uuid="b413a938-6bbf-49e9-943e-91bbe29e9fbd" name="Silicon" pid=5625 uid=1000 result="success"
Jul  8 11:21:28 Z-ROG-18 NetworkManager[2640]: <info>  [1562577688.9663] vpn-connection[0x56398883c530,b413a938-6bbf-49e9-943e-91bbe29e9fbd,"Silicon",0]: Started the VPN service, PID 6460
Jul  8 11:21:28 Z-ROG-18 NetworkManager[2640]: <info>  [1562577688.9851] vpn-connection[0x56398883c530,b413a938-6bbf-49e9-943e-91bbe29e9fbd,"Silicon",0]: Saw the service appear; activating connection
Jul  8 11:21:29 Z-ROG-18 NetworkManager[2640]: <error> [1562577689.0039] vpn-connection[0x56398883c530,b413a938-6bbf-49e9-943e-91bbe29e9fbd,"Silicon",0]: Failed to request VPN secrets #3:
No agents were available for this request.
Jul  8 11:21:29 Z-ROG-18 NetworkManager[2640]: <info>  [1562577689.0101] vpn-connection[0x56398883c530,b413a938-6bbf-49e9-943e-91bbe29e9fbd,"Silicon",0]: VPN service disappeared
...
The VPN is working under Budgie/Gnome(through nm-applet and the control center too). Please let me know if I can help!

**Comment by JohnGebbie** [comment] 2019-07-08 13:26
Jul  8 14:22:03 john-desktop NetworkManager[808]: <info>  [1562592123.1700] audit: op="connection-activate" uuid="178f0eee-7373-47f9-90fe-6f91262ded0a" name="nl-protonvpn" pid=5698 uid=1000 result="success"
Jul  8 14:22:03 john-desktop NetworkManager[808]: <info>  [1562592123.1852] vpn-connection[0x55557a8883f0,178f0eee-7373-47f9-90fe-6f91262ded0a,"nl-protonvpn",0]: Started the VPN service, PID 6807
Jul  8 14:22:03 john-desktop NetworkManager[808]: <info>  [1562592123.2019] vpn-connection[0x55557a8883f0,178f0eee-7373-47f9-90fe-6f91262ded0a,"nl-protonvpn",0]: Saw the service appear; activating connection
Jul  8 14:22:03 john-desktop NetworkManager[808]: <error> [1562592123.2117] vpn-connection[0x55557a8883f0,178f0eee-7373-47f9-90fe-6f91262ded0a,"nl-protonvpn",0]: Failed to request VPN secrets #3: No agents were available for this request.
Jul  8 14:22:03 john-desktop NetworkManager[808]: <info>  [1562592123.2135] vpn-connection[0x55557a8883f0,178f0eee-7373-47f9-90fe-6f91262ded0a,"nl-protonvpn",0]: VPN plugin: state changed: stopped (6)

**Comment by kgilmer** [comment] 2019-07-09 03:34
This seems related: https://bugzilla.redhat.com/show_bug.cgi?id=1394977

**Comment by kgilmer** [comment] 2019-07-09 03:52
I have verified that running `nm-applet` causes a password dialog to be presented when I try and start my fake VPN.  A short term fix may be to add this to your i3 config to have it launch on start, however there may be side effects to this.  If you want to give it a try, add this line to the bottom of your `~./config/i3-regolith/config` file:

`exec --no-startup-id /usr/bin/nm-applet`

**Comment by kgilmer** [comment] 2019-07-09 03:57
This issue also looks interesting: https://github.com/clearlinux/distribution/issues/205

Since this problem does not occur w/ in `ubuntu-session` I suspect a service that is loaded there is not being loaded w/ Regolith.  I'll have to setup a machine to learn more.

**Comment by KatonaZsolt** [comment] 2019-07-09 20:39
Success with the nm-applet launch on start. This solution is perfectly fine for me, thanks a lot!

**Comment by kgilmer** [comment] 2019-07-14 01:11
Closing, looks like using nm-applet is a fix for this issue.

**Comment by vanboom** [comment] 2019-08-09 22:10
This fix worked for me also, thanks for posting it.

**Comment by vanboom** [comment] 2019-08-25 15:41
The config file might also be in ~/.config/regolith/i3/config

**Comment by maxx** [comment] 2020-01-17 03:00
This solution allows networkmanager to prompt you for a password, but it still does not allow you to store the password.

**Comment by gnzlbg** [comment] 2020-02-16 12:25
This fix did not work for me. I added:

```
exec --no-startup-id /usr/bin/nm-applet
```

to `~/.config/regolith/i3/config` (which did not exist - that's the only line this file has in my system), and when restarting the computer, I get the following error:

```
i3 Error: Status_command not found (exit 127)
```

The desktop then becomes unusable, and typing `super+enter` does not open a terminal, and that there is no other way to open one. I had to restart again and log into the Ubuntu desktop, to be able to remove that line. 

This is something that should "just work", and not require the user to meddle with configuration files, so IMO this issue should be reopened.

**Comment by vanboom** [comment] 2020-02-16 18:16
This fix stopped working for me as well along the way after an update.

**Comment by kgilmer** [comment] 2020-02-16 18:30
@gnzlbg , you'll need to copy the entire i3 config file and then add your change.  [See here](https://regolith-linux.org/docs/howto/stage-configs/#i3-config) for details.  You can verify which config file i3 is loading with `i3 --moreversion`.

@vanboom can you be more specific?  Can you check and see if `nm-applet` is running in the background or not?

**Comment by 7system7** [comment] 2020-02-29 09:22
Same issue here. And I added this magic line to my config

```
exec --no-startup-id /usr/bin/nm-applet
```

// OFF
Btw, right here, the copy of the config files are also not working and I don't know why... I tried [this](https://regolith-linux.org/docs/howto/stage-configs/#i3-config) and [this](https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Stage-your-own-version-of-Regolith-configuration-files) documentation
And there is no real solution for this problem in github nor the stackoverflow. So, I created my configs in global config files. :disappointed: 

```
$ ls -la ~/.config/regolith/i3/config
-rw-r--r-- 1 system7 system7 15K febr  28 18:37 /home/system7/.config/regolith/i3/config

$ i3 --moreversion
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 3807)abort…)
Loaded i3 config: /home/system7/.config/regolith/i3/config (Last modified: 2020. febr. 28., péntek, 18:37:12 CET, 52752 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

I also tried these dirs and there is no success:
 -  ~/.i3/config
 - ~/.config/i3/config

__I like the idea of i3 and regolith, I used it for 1.5 week and it was fun. Maybe it will be a great desktop solution for professionals too. So keep it on, guys!__ :+1: 
BUT sadly, it seems, it is unstable for serious work right now. For every special settings (like the VPN) I have to dig the OS files in terminal or the internet and I do not have time for it. :disappointed: Maybe I made a mistake with the ubuntu base system, I don't know but the Ubuntu GNOME session works like charm.

**Comment by kgilmer** [comment] 2020-03-01 05:15
Thanks for the feedback @7system7 .  I understand your perspective.  If I or someone else is able to get setup w/ a VPN and do some testing and produce a better setup guide, I'll let you know!  :smile: :+1:

**Comment by Minalan** [comment] 2020-03-06 03:03
I don't know what is causing it, but I think there may be something wrong with the way NetworkManager is being run in Regolith vs. Ubuntu.
When tailing the /var/log/syslog I see a ton of messages like this:

> Mar  5 21:00:56 **** NetworkManager[1280]: <warn>  [1583463656.4464] error requesting auth for org.freedesktop.NetworkManager.settings.modify.hostname: Authorization check failed: Failed to open file “/proc/28073/status”: No such file or directory

Those errors do not occur in the standard Ubuntu session.

**Comment by dennis-reiter** [comment] 2020-03-16 08:47
I experienced the same problems with my vpn. Starting nm-applet did not solve the problem but when I started the nm-applet from my shell, I saw it complaining about a missing **/usr/lib/NetworkManager/nm-openconnect-auth-dialog**.
This dialog is provided by **network-manager-openconnect-gnome**. So
```
sudo apt install network-manager-openconnect-gnome

sudo systemctl restart NetworkManager.service
```
Now vpn is working!

**Comment by kgilmer** [comment] 2020-03-17 00:59
That's great to hear @dennis-reiter !  @Minalan @7system7 @vanboom @maxx are you able to verify @dennis-reiter 's fix?

**Comment by JensPfeifle** [comment] 2020-03-17 10:44
I am getting a similar message when trying to toggle the VPN from the control panel:
```
Mar 17 11:40:42 t490jp NetworkManager[3842]: <info>  [1584441642.2018] audit: op="connection-activate" uuid="c004e577-8ab7-4761-8263-6659f703c27c" name="MyVPN" pid=16969 uid=1000 result="fail" reason="Not authorized to control networking."
```
Update, restarts, and fixes mentioned in this thread have not helped so far. Oddly enough it was working yesterday...

**Comment by newtorob** [comment] 2020-03-18 14:59
@dennis-reiter's fix worked for me

**Comment by TSchattschneider** [comment] 2020-04-02 11:01
Same problem when trying to use my university opneconnect-VPN, using `exec --no-startup-id /usr/bin/nm-applet` worked.

**Comment by imarchev** [comment] 2020-04-02 22:51
My issue was caused by the previous installation of **i3wm**. I had  a config for i3wm located in `/.config/i3/config` with the same row `exec --no-startup-id /usr/bin/nm-applet`
The fix that works for me was to remove np-applet row from i3wm config and add it to `/.config/regolith/i3/config` and after Logout-Login I was able to switch-on VPN

**Comment by JonathanCasters** [comment] 2020-04-03 08:37
When I do the nm-applet in my terminal I get these error's:
![error_nm_applet](https://user-images.githubusercontent.com/48123172/78340749-e96cfe80-7596-11ea-8ec6-9b208e8c8fc9.png)
I added the nm-applet commando in the config files, but it didn't work, so I tried this in the terminal, and got those errors. I still can't activate my VPN connection. It pops right back to off when I push it. So what else can I try to make this work?

**Comment by masdarzulfikar** [comment] 2020-04-05 01:32
in my case, the config file is in the: `/etc/regolith/i3/config`
I add the line `exec --no-startup-id /usr/bin/nm-applet` and it worked.

**Comment by kgilmer** [comment] 2020-04-15 03:32
Hello VPN team! :smile: , is anyone here able to test @dennis-reiter 's update to the VPN blocklet?  

https://github.com/regolith-linux/regolith-i3xrocks-config/pull/32

**Comment by gdeflaux** [comment] 2020-05-02 15:07
Confirming that installing the additional packages 

```
sudo apt install network-manager-openconnect-gnome
sudo systemctl restart NetworkManager.service
```

and adding `/usr/bin/nm-applet` in my i3 config file worked. I can start my VPN from the gnome control center. 

I can't get the openvpn block to show anything else than `VPN: down`. I tried the block from the `master` branch.

Also, I am unable to locate de PID file of the VPN connection, which seems to be what the script is looking for. The folder `/run/openvpn` is empty although I can definitely confirm that I am connected to a VPN.

**Comment by kgilmer** [comment] 2020-05-22 18:36
Based on recent feedback it appears that people are able to enable VPN.  Closing the issue.  For users still facing issues w VPN, kindly open a new ticket and fill out the required fields.

**Closed by kgilmer** 2020-05-22 18:36 UTC
Labels: bug, question
