### ISSUE TITLE
Icons appeared on the desktop and the system tray disappeared after the update.

### ISSUE THREAD

**Issue by ozgreat** [regolith-linux/regolith-desktop#347] opened 2020-04-27 11:32 UTC
I do:
sudo do-release-upgrade -d
And icons appeared on the desktop and the system tray disappeared after the update.
![image](https://user-images.githubusercontent.com/32894068/80367401-aea76f00-8893-11ea-9d00-6d74f3f60d09.png)
![image](https://user-images.githubusercontent.com/32894068/80367439-c4b52f80-8893-11ea-8fa3-a29ed73e8dfc.png)
How to get things back the way they were without reinstall distro?

**Comment by kgilmer** [comment] 2020-04-27 15:16
Hi @ozgreat , to resolve the weird desktop issue, remove the directory `~/.config/regolith/flags`, and log back in.  To add status indicators to your bar, see this: https://regolith-linux.org/docs/howto/add-remove-blocklets/

**Comment by funkythings** [comment] 2020-04-27 15:46
After running the removal with `rm -rf ~/.config/regolith/flags` and logging back in, the icons are still nowhere to be found. Even after reboot!

**Comment by DennisJLi** [comment] 2020-04-27 17:06
Hey @kgilmer , tried running those steps, installed the i3xrocks packages, and ran `regolith-look refresh`, but still nothing shows up at the bar on the bottom. I got the following error when running the command, but can't seem to find any config mentioning "headerbar" in the standard regolith i3 configs or the ones in mine. Does anyone know how to fix this?

```
> $ regolith-look refresh
> Updating already existing 'Regolith' profile
No such key “headerbar”
```

**Comment by kgilmer** [comment] 2020-04-27 19:15
@DennisJLi can you try these steps: https://regolith-linux.org/docs/getting-started/install/#upgrading-with-customizations

**Comment by nicolas471** [comment] 2020-04-27 19:34
For the tray icons(eg slack) come back is necessary install something?

**Comment by DennisJLi** [comment] 2020-04-28 00:22
Awesome, thanks @kgilmer , that worked!

**Comment by kgilmer** [comment] 2020-04-29 01:59
@nicolas471 , I do not use tray icons myself, but have tested launching nm-applet like this succesfully, and other users have reported general success with this as well: `$ dbus-launch nm-applet`.

**Comment by nicolas471** [comment] 2020-04-29 12:51
@kgilmer if execute the programs with `dbus-launch` the icon appears. Any way to solve this running the programs normaly?

**Comment by callebjorkell** [comment] 2020-04-29 17:49
I had this problem with the systray missing in ubuntu 19.04 as well, and then it went away for 19.10. I did do a clean install of ubuntu + regolith at this time though, so that could be a part of it. However, I did a dist-upgrade just like @ozgreat and now the systray is missing again. To me, it has seemed like a dbus issue, because I've also seen other issues related to inter application communication:
* Sometimes the lockscreen trigger (the new one using dbus-send) stops reacting.
* If I launch nm-applet with dbus-launch, it does appear in the systray but when connecting to VPN, it is not able to access the keyring to get the passwords.
* More like this that I cannot pull from my head right now :smile: 

It almost feels like there would be multiple dbus daemons, and it's working in a split brain mode, but I'm not knowledgeable enough in how dbus works to be able to verify that this is the issue. Could thi be a reason, and what could I do to verify?

**Comment by callebjorkell** [comment] 2020-04-29 18:43
Actually, after skimming the man pages, using `dbus-launch` at all in this way seems to me to be wrong; It will start a new `dbus-daemon` which in practice will be handled as a new session as far as I understand from the text. The daemon will also not exit with the process that it launches, which would further support that suspicion.

**Comment by kgilmer** [comment] 2020-04-30 03:03
Interesting info @callebjorkell !  I did not think to read the man page of `dbus-launch` but that does sound like a good lead.  I will look into this more.

**Comment by kgilmer** [comment] 2020-04-30 04:51
I did some more reading about dbus and have more understanding, and a suspicion that dbus isn't launching properly to support gnome services like the system tray.  Here is how I got `nm-applet` to work properly without giving it it's own dbus:

Launch a dbus-daemon:

```bash
$ DBUS_VERBOSE=1 dbus-daemon --session --print-address
unix:abstract=/tmp/dbus-L3rpSvk7N4,guid=c30eff74f66431009694b7b95eaa5637
```

Launch nm-applet:

```bash
$ DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-L3rpSvk7N4,guid=c30eff74f66431009694b7b95eaa5637 nm-applet
```

Observe that the task tray has a member, and the following output from the daemon process:
```bash
^[[D^Xdbus-daemon[29033]: [session uid=1000 pid=29033] Activating service name='org.gtk.vfs.Daemon' requested by ':1.0' (uid=1000 pid=29614 comm="nm-applet " label="unconfined")
dbus-daemon[29033]: [session uid=1000 pid=29033] Successfully activated service 'org.gtk.vfs.Daemon'
```

Based on this (non-conclusive) experiment, my guess is that a session dbus instance is not available or the environment variable used to direct apps to the appropiate bus is missing.  The latter theory has supporting evidence that on my 18.04 machine, `DBUS_SESSION_BUS_ADDRESS` has a value by default, but in my 20.04 machine, it is undefined.

Given this, it would seem that whatever was setting DBUS_SESSION_BUS_ADDRESS is no longer doing so.  There have been breakages in Regolith in the past due to systemd related changes to gnome.  Perhaps this is also the case here.  It's tempting to just start a session-based dbus instance when loading the regolith session and setting the environment variable then, but I would prefer to understand the root cause in greater detail before implementing any solutions.

Thoughts?

**Comment by ozgreat** [comment] 2020-04-30 20:21
> Hi @ozgreat , to resolve the weird desktop issue, remove the directory `~/.config/regolith/flags`, and log back in. To add status indicators to your bar, see this: https://regolith-linux.org/docs/howto/add-remove-blocklets/

That's works for me with icons issue, but indicators on the bottom bar still don't showing.

**Comment by kgilmer** [comment] 2020-05-01 03:20
@ozgreat , what do you get from `apt list --installed | grep i3xrocks-` and `find ~/.config/regolith` and `i3 --moreversion`?

**Comment by callebjorkell** [comment] 2020-05-01 12:22
At least I do have the environment variable set on 20.04 as well:
```
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
```
Not sure then if that has to do with the fact that I upgraded instead of performed a clean install.

**Comment by callebjorkell** [comment] 2020-05-01 13:30
Is there any more information I could provide? I was trying to look through the gdm logs, and it would seem at least that the environment variable is also set up there before the i3 session is launched. Maybe there's a gnome service that handles the tray that starts too quickly, or doesn't register with the dbus-daemon properly? It does seem like most things actually do use the same systemd provided dbus, so overall things seem to be working..? It's just the system tray that I've noticed to consistently not work.

**Comment by ozgreat** [comment] 2020-05-01 16:22
> @ozgreat , what do you get from `apt list --installed | grep i3xrocks-` and `find ~/.config/regolith` and `i3 --moreversion`?
```
apt list --installed | grep i3xrocks-                          Пт 01 мая 2020 16:20:37

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

i3xrocks-battery/focal,now 3.0.10 amd64 [установлен]
i3xrocks-cpu-usage/focal,now 3.0.10 amd64 [установлен]
i3xrocks-focused-window-name/focal,now 3.0.10 amd64 [установлен]
i3xrocks-keyboard-layout/focal,now 3.0.10 amd64 [установлен]
i3xrocks-media-player/focal,now 3.0.10 amd64 [установлен]
i3xrocks-memory/focal,now 3.0.10 amd64 [установлен]
i3xrocks-net-traffic/focal,now 3.0.10 amd64 [установлен]
i3xrocks-nm-vpn/focal,now 3.0.10 amd64 [установлен]
i3xrocks-openvpn/focal,now 3.0.10 amd64 [установлен]
i3xrocks-temp/focal,now 3.0.10 amd64 [установлен]
i3xrocks-time/focal,now 3.0.10 amd64 [установлен]
i3xrocks-volume/focal,now 3.0.10 amd64 [установлен]
i3xrocks-weather/focal,now 3.0.10 amd64 [установлен]
i3xrocks-wifi/focal,now 3.0.10 amd64 [установлен]
regolith-i3xrocks-config/focal,now 3.0.10 amd64 [установлен, автоматически]
 I  ~  find ~/.config/regolith                              
/home/ozgreat/.config/regolith
/home/ozgreat/.config/regolith/i3
/home/ozgreat/.config/regolith/i3/config
/home/ozgreat/.config/regolith/i3xrocks
/home/ozgreat/.config/regolith/i3xrocks/conf.d
/home/ozgreat/.config/regolith/i3xrocks/conf.d/30_battery
/home/ozgreat/.config/regolith/i3xrocks/conf.d/01_setup
/home/ozgreat/.config/regolith/i3xrocks/conf.d/20_keyboard-layout
/home/ozgreat/.config/regolith/i3xrocks/conf.d/40_wifi
/home/ozgreat/.config/regolith/i3xrocks/config
/home/ozgreat/.config/regolith/flags
/home/ozgreat/.config/regolith/flags/ui-fingerprint
/home/ozgreat/.config/regolith/flags/show-shortcuts
/home/ozgreat/.config/regolith/flags/term-profile
/home/ozgreat/.config/regolith/flags/first-time-setup-r1-4
 I  ~  i3 --moreversion                                             
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 2574)abort…)
Loaded i3 config: /home/ozgreat/.config/regolith/i3/config (Last modified: Пн 23 мар 2020 19:56:25, 3363883 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

**Comment by kgilmer** [comment] 2020-05-01 16:28
I have moved the system tray issue to a separate issue.  Please see here for a workaround if you want this resolved before a general fix is released: https://github.com/regolith-linux/regolith-desktop/issues/364#issuecomment-622456865

**Comment by timjrobinson** [comment] 2020-05-02 05:52
I'm getting the same issue as @DennisJLi where when refreshing it says:

```
> $ regolith-look refresh
> Updating already existing 'Regolith' profile
No such key “headerbar”
```

I tried following https://regolith-linux.org/docs/howto/add-remove-blocklets/ only copying the 80_battery item but it's still giving the same error.

**Comment by kgilmer** [comment] 2020-05-02 19:25
@ozgreat , you have your own copy of the i3 config file (`/home/ozgreat/.config/regolith/i3/config`).  If this was copied before upgrading to 1.4, that would be the problem.  [See here](https://regolith-linux.org/docs/getting-started/install/#upgrading-with-customizations) about resetting config files to 1.4 defaults and one it's working you can re-integrate any changes.

**Comment by nickgrim** [comment] 2020-05-08 15:05
If you're using a v1.4 config file for `i3`, you will probably need to set:
```
i3-wm.bar.trayoutput: primary
```
…in your `~/.config/regolith/Xresources` file.

**Comment by matiasnoriega** [comment] 2020-05-15 20:33
> Hi @ozgreat , to resolve the weird desktop issue, remove the directory `~/.config/regolith/flags`, and log back in. To add status indicators to your bar, see this: https://regolith-linux.org/docs/howto/add-remove-blocklets/

Deleting this directory and logging back again solved the gnome icons appearing on the desktop! Thank you very much

**Comment by kgilmer** [comment] 2020-05-16 05:43
Closing this issue due to it being unclear who's still got a problem.  If anyone on this issue is still having difficulties, kindly create an individual issue.

**Closed by kgilmer** 2020-05-16 05:43 UTC
Labels: bug

**Comment by mh4nx7net** [comment] 2020-06-26 07:34
hi, iam here. please reopenup.. still get the same issues

**Comment by kgilmer** [comment] 2020-06-28 01:31
@mh4nx7net there are several issues here. Please create your own issue and explain your specific problem please. 😊
