### ISSUE TITLE
Fractional scaling missing on Ubuntu 19.10

### ISSUE THREAD

**Issue by Filip-K** [regolith-linux/regolith-desktop#173] opened 2019-11-20 15:52 UTC
Hi! When I log in to a normal Ubuntu session, fractional display scaling (obtained via a xrandr hack, from what I know) can be chosen in the display settings. In a Regolith session, fractional scaling options are missing (I only have 100% and 200%, neither of which is usable on my ThinkPad T480s with a HiDPI screen). Is this by design or is there something wrong with my setup?

**Comment by kgilmer** [comment] 2019-11-20 16:16
I have other scaling options available (see screenshot).  How did you install Regolith?  (PPA / LiveCD) and did you start with 19.10 or upgrade from an earlier version?

![image](https://user-images.githubusercontent.com/49683/69256273-1253a080-0b6e-11ea-9342-e48e1193955d.png)

**Comment by ploum** [comment] 2019-11-20 20:48
Fractional scaling has not been enabled by default in 19.10.

See http://ubuntuhandbook.org/index.php/tag/fractional-scaling-ubuntu-19-10/ to enable it.

**Comment by Filip-K** [comment] 2019-11-20 21:50
@kgilmer Your screenshot shows more integer (multiples of 100%) scaling options than I have, but no fractional scaling options (say, 150%).

@ploum  Indeed, I just remembered one has to enable fractional scaling with `gsettings set org.gnome.mutter experimental-features "['x11-randr-fractional-scaling']"`, like the link you sent suggests. However, this setting has no effect in Regolith (which is understandable, since we don't use Mutter, right?) and thus does not solve the issue.

What kinda-solves the issue for me is doing the [xrandr hack](https://www.valhalla.fr/2018/07/14/hidpi-on-gnome-desktop/) plus modifying some font sizes. That is, after applying the hack I stage and edit my copy of `/etc/regolith/styles/typeface-sourcecodepro` to increase the rofi and terminal typeface sizes by the percentage I have set in my display settings (2 in my case). Without the last step, the text in the terminal and the Super+Space menu is tiny.

**Comment by justinmoon** [comment] 2020-01-09 07:44
This would be really nice. I've been using Regolith for 2 weeks and loving it.

Biggest issue so far is that 100% is too small for my laptop, and 200% is too big.

**Comment by SteadBytes** [comment] 2020-01-14 06:29
:+1:  This is the only thing stopping me from running regolith full time - my work laptop (Thinkpad X1 carbon) has a HiDPI screen and as @justinmoon says, 100% is tiny but 200% is too big :sweat_smile: Fractional scaling is available in a normal Gnome session however.

**Comment by justinmoon** [comment] 2020-01-14 19:18
@SteadBytes I also have Thinkpad X1 Carbon, btw. Perhaps it's something to do with this specific machine ...

**Comment by kgilmer** [comment] 2020-01-15 04:48
There may be a difference due to Regolith using gnome-flashback and ubuntu-session using gnome-shell, but I cannot say for sure.  I believe you can get the same effect by setting Xresources Xft.dpi value, as described here: https://wiki.archlinux.org/index.php/HiDPI#X_Resources

Anyone care to give it a try and report back?

**Comment by SteadBytes** [comment] 2020-01-15 06:24
@kgilmer Unfortunately I've tried that and it has had no effect :thinking:

**Comment by justinmoon** [comment] 2020-01-15 09:36
I've tried messing with Xft.dpi as well and it never does anything. I'm not sure whether I'm doing it right ...

**Comment by GijsVermarien** [comment] 2020-01-16 09:47
I looked into this some time ago, indeed because gnome-flashback does not use Mutter, the fractional scaling cannot be enabled. For me it works to create an `.Xresources` file with in it:
```
Xft.dpi: 96
```
After that you have to log in and out to see the changes.

**Comment by mapitman** [comment] 2020-03-09 01:46
Has anyone else figured out how to do fractional scaling? I've tried setting it with
```
xrandr --dpi 96
```

I've also tried using the `.Xresources` file and neither one does anything.

**Comment by GijsVermarien** [comment] 2020-03-09 09:07
So far I have found the following solution to be the best, you can use xrandr --scale in order to get a fractional scaling:
```
xrandr --output HDMI-2 --scale 0.8x0.8
```
where 0.8x0.8 seems to work fine for me on a 32 inch, 4k screen. But you can try some other values. Its not perfect but it is my current working solution.

**Comment by SteadBytes** [comment] 2020-03-14 07:15
`Xft.dpi` still does not work for me (even after updating to the latest release nor does `xrandr --dpi` . Changing the *scale* using `xrandr --scale` is undesirable as it reduces quality of the display (blurry text e.t.c)

**Comment by kgilmer** [comment] 2020-03-14 15:57
What about gnome tweaks?  `sudo apt install gnome-tweaks`

![image](https://user-images.githubusercontent.com/49683/76685536-d5566280-65d1-11ea-90f4-335c619f2fcc.png)

**Comment by mcarlin** [comment] 2020-04-04 19:41
Gnome tweaks appears to work for me, thanks!

**Comment by moritzheiber** [comment] 2020-05-22 18:20
@Filip-K Focal Fossa definitely has proper scaling support, is it okay to close this issue now?

**Comment by Filip-K** [comment] 2020-05-22 18:42
You mean in Focal one can select fractional scaling in a Regolith session in the same way one does in a stock session? (I didn't upgrade yet so can't check myself.) If so, then yes, we can close. Thanks!

**Comment by moritzheiber** [comment] 2020-05-22 18:50
Yup, exactly. Please feel free to open another issue if the problem persists after the upgrade :slightly_smiling_face:

**Closed by moritzheiber** 2020-05-22 18:50 UTC
Labels: enhancement, question

**Comment by paolomainardi** [comment] 2020-06-07 16:44
It seems that on Focal is still not possible to have fractional scaling, even tough is enabled:

![image](https://user-images.githubusercontent.com/8747/83974596-db1cc500-a8ee-11ea-9c7f-e3589353f4ec.png)

It works fine on Gnome.

**Comment by moritzheiber** [comment] 2020-06-07 16:49
@paolomainardi Please open another issue if you think you’ve encountered a similar issue. Thanks!

**Comment by paolomainardi** [comment] 2020-06-07 16:59
Hi @moritzheiber i can do it, but it is the same issue, not a similar one.

**Comment by moritzheiber** [comment] 2020-06-07 17:26
@paolomainardi This issue is about 19.10, yours is referring to 20.04. That's definitely a different environment (and even different Regolith release)

**Comment by paolomainardi** [comment] 2020-06-07 17:32
Ok fair enough, opening a new issue, thanks.

**Comment by SteadBytes** [comment] 2020-06-08 07:37
@paolomainardi I can confirm that this is still an issue in 20.04 as I have recently upgraded. Please could you link your issue here for reference?

**Comment by Philipp0205** [comment] 2022-01-03 13:31
Can config this still exists in 21.10 but the workaound from @kgilmer with gnome-tweaks worked.
