### ISSUE TITLE
Theme reset after "High Contrast"

### ISSUE THREAD

**Issue by WuerfelDev** [regolith-linux/regolith-desktop#13] opened 2019-04-24 23:25 UTC
After toggling High Contrast in Settings->Universal Access the theme gets set to Ubuntu Ambiance
Icons also change to its default

**Comment by kgilmer** [comment] 2019-04-25 02:49
This is probably by design of gnome-settings.  To have Regolith restore this configuration on your next login, delete files in your home directory starting with `~/.regolith-init-flag-`, and then logout.  I'm not sure if there is a systematic fix for this issue, as I don't want to prevent users from being able to change these settings.

**Closed** 2019-04-25 08:41 UTC

**Comment by plagasul** [comment] 2019-07-01 16:08
I am experiencing this aswell, and the reset remains after disabling high contrast even after logout or reboot. I do not seem to have any file starting with .regolith-init-flag- in my home folder.

**Comment by kgilmer** [comment] 2019-07-02 04:18
Hi @plagasul , the flags have moved from your root directory into `~/.config/i3-regolith`.  Here's what mine looks like:
```
$ ls ~/.config/i3-regolith/
config  config-flag-1.24-1ubuntu1ppa1  config-flag-1.25-1ubuntu1ppa1  ftue-flag-4.16-1ubuntu18ppa4
```

Removing all files in this directory (assuming there are no changes you don't want to lose) and then logging out and back in again should restore your system as if Regolith was just installed.

Please let me know if this isn't clear or it doesn't resolve your issue.

**Comment by plagasul** [comment] 2019-07-02 16:43
Hello, 
I would like to keep 'config' as I've modified it, if possible. 
Is there anything in there related to the theme?
Thank you

**Comment by skostojohn** [comment] 2020-04-18 23:56
I am seeing this issue as well after toggling high-contrast :(

Under `.config/regolith` I have a 'flags` directory - is that the one I should empty to fix this?

**Comment by kgilmer** [comment] 2020-04-19 01:47
Hi @skostojohn , just remove the `~/.config/regolith/flags` directory and log back in for a reset.

**Comment by skostojohn** [comment] 2020-04-19 04:41
Thanks Ken - that did the trick!
