### ISSUE TITLE
Regolith ISO not recognized as bootable.

### ISSUE THREAD

**Issue by etrigan63** [regolith-linux/regolith-desktop#23] opened 2019-06-12 04:00 UTC
I burned the regolith ISO file to a USB stick as per the instructions and when I try to boot from it, neither of my two laptops recognize it.

**Comment by kgilmer** [comment] 2019-06-12 04:07
Hello! I have not seen this problem before. What url did you use to
download the iso? What program did you use to make the USB drive?

**Comment by etrigan63** [comment] 2019-06-12 04:58
I downloaded the image from the links on regolith-linux.org and used etcher to burn the image. If I insert the USB stick in a running system, it is recognized and I can browse the drive. If I try to boot from it, the USB stick is not recognized. I tested with two different USB drives.

**Comment by etrigan63** [comment] 2019-06-12 05:46
UPDATE: I used Rufus on a Windows PC to create the USB stick and it was recognized. Rufus reported that two files were missing to make the image bootable and it downloaded them automatically. Creating a bootable drive using Etcher in Linux does not work. The one created with Rufus worked and I was able to install it on my laptop.

**Comment by kgilmer** [comment] 2019-06-12 13:50
Hi @etrigan63 thanks for performing and documenting your troubleshooting steps.  I have tested both r1 and r1.1 ISOs with "Startup Disk Creator" on Ubuntu and did not have any issues.  Based on your steps here, I also tried etcher for the first time with r1.1 ISO and was able to boot from the drive on my laptop without problems.  So, I cannot reproduce your problem.  However, I have had this exact same issue in the past w/ various LiveCD images.  I have never found a root cause but found that simply swapping out USB drives until I found one that worked eventually got me over the issue.  I wish I had a better handle on this problem!

I'm happy to hear Rufus on Windows worked out for you, and hope you like Regolith!

**Comment by etrigan63** [comment] 2019-06-12 15:40
Both of the USB sticks I tested had Manjaro on them. The Manjaro ISO image is a little wonky on its setup. I will test with a fresh USB stick today and see what happens. Rufus repartitions and formats the USB stick to FAT32 and then copies the files over, unlike Etcher which used dd in the background.

**Comment by pavelexpertov** [comment] 2019-06-16 22:10
Hello!
I had the same (or at least very close issues) with regards to not seeing a usb drive as a live session one.
Basically, I would be able to select the flash drive and then see Ubuntu splash screen and then an error would spit out saying the drive is not bootable (or some such).
I used etcher, which I downloaded today of this message, on elemntary 5.0 and I had manjaro being bootable before.
However, I did an experiment and I think I found the cause: if you plug the flash drive via an extension usb (e.g. a keyboard with its own usb ports), then the system doesn't recognise the drive as bootable. Then I plugged it into the normal usb port on my PC case and it worked!
I assume the best solution is to leave a side note on the downloads page of the website to say don't plug the drive via an extension cable or some such thing.

**Comment by kgilmer** [comment] 2019-06-23 16:40
@etrigan63 when you were having your problems was the usb drive attached to hub as mentioned by @pavelexpertov ?

**Comment by etrigan63** [comment] 2019-06-23 18:23
@kgilmer Yes I was running this from a powered USB 3.0 hub. I have installed many, many operating systems from it, I am certain it's not the problem. Again Rufus reported that two files were missing to make it bootable.

**Comment by pavelexpertov** [comment] 2019-06-25 18:29
Hmmmm. In that case, @kgilmer, it sounds like it's a hit and miss with the hubs if it's true what you are saying with regards to running off live sessions from the usb hub. Furthermore, what two files in particular did you not find? @kgilmer, is there any quick source material you could recommend that could explain how to burn images on live usbs, especially for distros and how they work in bootable mode? I am really noob at this, but I would like to check it out how it's usually set up.

**Comment by kgilmer** [comment] 2019-06-26 04:38
Absolutely @pavelexpertov .  I've updated the web page with links to tutorials that are the same way that I have flashed USB drives and installed Ubuntu.  Here they are:

https://tutorials.ubuntu.com/tutorial/tutorial-install-ubuntu-desktop#0
https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-ubuntu#0

**Comment by ArchiFleKs** [comment] 2019-06-30 21:17
Hi, I think the issue is related to EFI boot only.

I add the same issue with UEFI boot. I tried a standard ubuntu 19.04 iso and it worked. But when creating an USB key with regolith it was impossible to make it UEFI boot. 

For both I used etcher.

I manage to boot and install regolith by manually formatting an USB key with GPT partition and then copy over the files form the ISO.

**Comment by kgilmer** [comment] 2019-07-01 02:39
Hmm, thanks for the additional information @ArchiFleKs .  I'll take a look more closely at the [tool I used create the ISO image](https://launchpad.net/cubic) and see if there is a known issue documented.  I cannot reproduce this problem so have no clear path to resolving it at this time.

**Comment by kgilmer** [comment] 2019-07-03 13:25
The Cubic developers have responded to [my bug report](https://bugs.launchpad.net/cubic/+bug/1834810).  I'll work with them and hopefully be able to root-cause this issue.

**Comment by valankar** [comment] 2019-07-05 06:35
Hi, just some more info in case it's useful. I was having this problem in VMWare using EFI boot and this ISO:

regolith-19.04.0-2019.05.26-desktop-amd64.iso

I switched VMWare to legacy BIOS and then it worked.

**Comment by mr-gosh** [comment] 2019-07-29 15:18
I can confirm that a "only UEFI" supporting notebook (a [schenker slim14](https://bestware.com/de/schenker-slim-14.html)) can not boot from the Regolith 1.1 USB Sticks.
You can try to reproduce the problem if you have a notebook where you deactivate the Compatibility boot mode (tested on an lenovo x1).

**Comment by kgilmer** [comment] 2019-07-30 03:52
Thanks for the information @valankar and @mr-gosh .  Now that the Xresources work is out I'll be working on a new LiveCD release.  I'll be sure to test your scenarios to see if my image will boot as expected.

**Comment by mr-gosh** [comment] 2019-07-30 06:38
Let me know if should test a bootimage for you...

**Comment by kgilmer** [comment] 2019-08-15 15:53
I feel it's time to seriously consider a new LiveCD release.  I've created a discussion on slack.

**Comment by RIZY101** [comment] 2019-08-17 00:08
I had this same problem. As stated before if you use etcher it does not work, but when you use rufus with the classic way of copying over the iso files rather than using dd it then does work.

**Comment by jc00ke** [comment] 2019-08-24 16:17
I created the boot disk using `dd` and it was not recognized. Pretty sure I had the blocksize set to 4M.

**Comment by ahoneybun** [comment] 2019-09-01 00:33
I used the Disks application (gnome disk) to make a live disk with the 19.04 image and it failed too. I've been using a Pop 19.04 install then add the PPA.

**Comment by JimmyRecard** [comment] 2019-09-08 16:32
I am also experiencing this issue on Asus e200h. Unfortunately, I don't have a Windows machine to try the Rufus trick. :(

Also, my device also uses mixed mode UEFI (32bit UEFI but 64bit CPU), so enabling the kernel flag CONFIG_EFI_MIXED=y in the next release would be appreciated; I believe this is the default from Ubuntu upstream, but noting it just in case it is not.

Thanks!

**Comment by kgilmer** [comment] 2019-09-08 16:38
I'm working on this issue presently, thanks everyone for the tips and feedback.

**Comment by kgilmer** [comment] 2019-09-09 14:22
I have a R1.2 LiveCD ISO available for testing that was built on a machine in UEFI mode.  I have verified that the volume boots from a USB device both in Legacy and UEFI modes.  The R1.1 ISO would not boot in both, so at least one issue was addressed.  **If anyone can test this image, I'd really appreciate it!**

https://sourceforge.net/projects/regolith-linux/files/regolith-linux-r1.2/

**Comment by JimmyRecard** [comment] 2019-09-09 15:09
The new ISO boots for me without issues all the way to the live session desktop. So, the boot issue is resolved for me.

At the risk of polluting this thread with off topic stuff, it does boot to GNOME desktop, I have to log out and select Regolith manually. Presumably that's an oversight, so just letting you know.

**Comment by etrigan63** [comment] 2019-09-09 18:58
Same results as JimmyRecard.

Carlos Echenique
*Photographer*
*Carlos Echenique Photography*
m: 305.219.2433
w: www.cephotographic.com  e: carlos@echenique.com

**Comment by kgilmer** [comment] 2019-09-10 04:55
Thank you @JimmyRecard  and @etrigan63 for testing the update!  Your help is appreciated.  If you'd like a regolith laptop sticker, email me a postal address to kgilmer at gmail.com and I'll send you one.

**Comment by kgilmer** [comment] 2019-09-11 13:48
I have updated the ISO so that it boots into the Regolith session now when you select "Try Regolith".  Thanks for letting me know @JimmyRecard .  I will now release this version.

**Closed by kgilmer** 2019-09-11 13:48 UTC
Labels: bug
